### ISSUE TITLE
[Question] How to test if I passed echoCanceler true and noiseSuppressor true

### ISSUE THREAD

**Issue by tplloi** [pedroSG94/rtmp-rtsp-stream-client-java#1084]
Hi @pedroSG94 
Please refer to this link https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/d598ad6f2d7d171d9d071a03c14ac45b49302b09/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L306
when I set echoCanceler true, noiseSuppressor true (case 1) and echoCanceler false and noiseSuppressor false (case 2), the player played well but I don't see any difference? Could you guy pls guide me how to test 2 cases?

**Comment by pedroSG94** [comment]
Hello,

It is really difficult to check. I only can tell you confirm that all is activated because if you device don't support it. That parameter is ignored. 
You can confirm it here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/audio/AudioPostProcessEffect.java#L61
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/audio/AudioPostProcessEffect.java#L81
