### ISSUE TITLE
Record video: frame loss 

### ISSUE THREAD

**Issue by AntonLipovtsev** [pedroSG94/rtmp-rtsp-stream-client-java#1085]
When recording video to local memory, there is a loss of frames for the first two seconds (switching between the statuses STARTED and RECORDING)

**Comment by pedroSG94** [comment]
Hello,

You are not lossing frames. The record init on RECORDING state, STARTED state means that you called to startRecord and you are waiting for a keyframe to init the record.
If you start record without stream, this wait should be instant because encoder start with a keyframe but, if you are streaming, I did a method to request a keyframe to encoder in order to do this wait short but in few cases the encoder could take time to do it.
Also, you can reduce iFrameInterval of prepareVideo (time in seconds to generate a keyframe) to 1 instead of 2 and this wait should be reduced.

**Comment by AntonLipovtsev** [comment]
Thanks!

**Comment by rokoblak24** [comment]
@pedroSG94 hello, I am not completely sure I understand the usage and order of the following functions, in case I want to start streaming and recording at the same time (i.e. user presses a button on the screen):
- `startRecord`
- `requestKeyframe`
- `startStream`

Right now, I start the stream, start the record, and I request the keyframe. However, this doesn't seem to do anything in terms of decreasing those skipped frames at the beginning of the recorded video. I tried rearranging those with no effect.

The only thing that made an effect was decreasing the iFrameInterval to 1 from the default of 2, however I suppose for the sake of bandwidth this is better kept at its default?

**Comment by rokoblak24** [comment]
Thank you and much appreciated for a quick reply! Will apply the suggestions and use the listener.

**Comment by rokoblak24** [comment]
@pedroSG94 hello, is there a way to determine when the streaming started after `rtmpCamera?.startStream` is called?
On the server side, the first couple of seconds are not captured, so I'm wondering if there's a way for me to listen to a callback in order to update the UI.
