### ISSUE TITLE
Implementing this library with USB Camera 

### ISSUE THREAD

**Issue by publioelon** [pedroSG94/rtmp-rtsp-stream-client-java#1088]
Hi, I am trying to implement this library with my SDK from a thermal USB camera for android, as it seems the other project was discontinued.  I tried this repository that uses your library on an endoscopy USB camera and it worked well, so I know there are only a few adjustments to be made. My SDK is fully java, so currently, my trouble is:

in the USBBase.java, I have the following error:
Cannot resolve method 'prepareVideoEncoder(int, int, int, int, int, boolean, int, com.pedro.encoder.video.FormatVideoEncoder)' 

and in RtmpUSB.java, the error is this:

Cannot resolve symbol 'SrsFlvMuxer'

Additionally, in the same file USBBase.java, these imports are not found:

import net.ossrs.rtmp.ConnectCheckerRtmp;
import net.ossrs.rtmp.SrsFlvMuxer;

**Comment by pedroSG94** [comment]
Hello,

Maybe the problem is that you are doing an import of the new library version.
Stream-USB-Test is using library version 1.5.0. You can check it here:
https://github.com/pedroSG94/Stream-USB-test/blob/master/app/build.gradle#L31
So, you have 3 options:
- import library in that version using gradle
- download zip of that version and add it to your project:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/releases/tag/1.5.0
- Use the last library version (2.1.7) and refactor RtmpUSB and USBBase to use it.

**Comment by publioelon** [comment]
thanks man, i managed to import the lib
