### ISSUE TITLE
切换摄像头时，如何调整rotation  ？

### ISSUE THREAD

**Issue by cdcdec** [pedroSG94/rtmp-rtsp-stream-client-java#110]
切换摄像头时，如何调整rotation？rotation=0，使用后置摄像头，图像正常；切换成前置摄像头后，头像是反的。

**Comment by pedroSG94** [comment]
If you use rtmpcamera1 with surfaceview or textureview you can change frontal camera rotation here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L305
I rotated frontal camera because normally all device return nv21 of frontal camera rotated 180 in this method.
