### ISSUE TITLE
TextureView deprecated

### ISSUE THREAD

**Issue by Reginer** [pedroSG94/rtmp-rtsp-stream-client-java#1143]
Hello , pedro :

Could you remove TextureView deprecated ?

I want to use this view . it works well in background no service .

Hope you can keep updating for TextureView .

**Comment by pedroSG94** [comment]
Hello,

TextureView and SurfaceView are deprecated using camera2 because OpenGlView is more flexible and you can avoid rotation problems (using camera1 it is not deprecated because you can support api 16/17).
I will fix bugs but no more. Any feature request related to that views will be discarded (basically it is in maintenance mode).

You can still use it without problems.
