### ISSUE TITLE
problem prepareVideo

### ISSUE THREAD

**Issue by liodali** [pedroSG94/rtmp-rtsp-stream-client-java#118]
Hi pedro ,i have error do you can help me ?
when i call rtmpBuilder.prepareVideo(160, 120, 25, 270 * 1024, false, 90)
i get this exception :Camera1Base: Streaming or preview stopped, ignored

**Comment by pedroSG94** [comment]
This isn't an exception only a log, you will see it when you call stopPreview while you are streaming.
prepareVideo method call this method to update camera resolution if you are in preview.
So the only way that you can see it is when you are streaming and call stopPreview or prepareVideo. You need call stopStream before it.

**Comment by nikhilpatil20** [comment]
the streaming is start and stop but camera is not display please help what should i do. and i am having one log message Camera1Base: Streaming or preview stopped, ignored dont know what to do please help

**Comment by pedroSG94** [comment]
Hello,

First of all, please, avoid comment on issues closed.
That means that you are calling stopPreview while you are streaming or when you have preview already stopped. Basically the method is ignored becuase you can't disable the preview (because you are streaming) or your preview is already stopped.
If you dont need a preview you can totally ignore the log but if you are no able to start the preview let me know:
Are you using app examples?  which one?
If you are not using app examples, can you share code used?
