### ISSUE TITLE
How to change image watermark and text  postion in screen in OpenGlRtmp.java

### ISSUE THREAD

**Issue by Rishabhsoti** [pedroSG94/rtmp-rtsp-stream-client-java#125]
How to change image watermark and text  postion in screen in OpenGlRtmp.java

**Comment by pedroSG94** [comment]
To change watermark you have this methods:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L568
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L583
This work for ImageStreamObject, GifStreamObject and TextStreamObject.

If you want change position of Android view filter you need create a Layout set your view in the layout and send layout to filter instead of only your view.
Example send Button in center of the screen.
In XML:
```
<RelativeLayout
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:id="@+id/rl_to_send"
      >
    <Button
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:text="Text to send"
        android:layout_centerInParent="true"
        />
  </RelativeLayout>
```
In Java code send RelativeLayout:
```
AndroidViewFilterRender androidViewFilterRender = new AndroidViewFilterRender();
androidViewFilterRender.setView(findViewById(R.id.rl_to_send));
rtmpCamera1.setFilter(androidViewFilterRender);
```
