### ISSUE TITLE
Does not send video. Exception thrown

### ISSUE THREAD

**Issue by mohsalsaleem** [pedroSG94/rtmp-rtsp-stream-client-java#13]
I tried the sample application. It only sends the audio. The video is not sent.
I used Samsung galaxy S6 running android 6.0.1
Same issue on Google Nexus 5 running 5.1.1

Here is the exception
com.pedro.rtmpstreamer E/SrsFlvMuxer: frame discarded, cant add more frame: 
                                                                     java.lang.IllegalStateException: Queue full
                                                                         at java.util.AbstractQueue.add(AbstractQueue.java:69)
                                                                         at net.ossrs.rtmp.SrsFlvMuxer$SrsFlv.flvFrameCacheAdd(SrsFlvMuxer.java:845)
                                                                         at net.ossrs.rtmp.SrsFlvMuxer$SrsFlv.writeRtmpPacket(SrsFlvMuxer.java:839)
                                                                         at net.ossrs.rtmp.SrsFlvMuxer$SrsFlv.writeAudioSample(SrsFlvMuxer.java:687)
                                                                         at net.ossrs.rtmp.SrsFlvMuxer.sendAudio(SrsFlvMuxer.java:220)
                                                                         at com.pedro.builder.RtmpBuilder.getAccData(RtmpBuilder.java:163)
                                                                         at com.pedro.encoder.audio.AudioEncoder.getDataFromEncoderAPI21(AudioEncoder.java:119)
                                                                         at com.pedro.encoder.audio.AudioEncoder.inputPcmData(AudioEncoder.java:98)
                                                                         at com.pedro.builder.RtmpBuilder.inputPcmData(RtmpBuilder.java:178)
                                                                         at com.pedro.encoder.input.audio.MicrophoneManager$1.run(MicrophoneManager.java:71)
                                                                         at java.lang.Thread.run(Thread.java:818)

Here, I've attached the full log.
[https://gist.github.com/mohsalsaleem/b176857179a4321fc981c60d44ed38fa](https://gist.github.com/mohsalsaleem/b176857179a4321fc981c60d44ed38fa)

**Comment by pedroSG94** [comment]
06-29 20:03:33.459 30659-31452/com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Video, size: 9936
06-29 20:03:33.479 30659-31452/com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Video, size: 9620

I can see in your log video packets after the error. 
The crash show when you have more than 20 video packets in queue and then discard this packets for sync video and preserve app memory.
I think that occurred because your server needed to much time for response but according with the log you should see stream normally after that.

The stream after the crash work or not?

**Comment by mohsalsaleem** [comment]
I did not see any video. Later I tried again and I could not stream any log with "RTMP Video" tag. The stream after crash did not work.

**Comment by pedroSG94** [comment]
Ok. My error i deleted a line in other commit.  Go to error catch and write queue.clear();
That should fix it. Í will update today

**Comment by pedroSG94** [comment]
Updated. Get last commit and check.

**Comment by mohsalsaleem** [comment]
See the attached log file after adding queue.clear()

[https://gist.github.com/mohsalsaleem/a2b59ec80ed07fdc84857e5e2b8d9aff](https://gist.github.com/mohsalsaleem/a2b59ec80ed07fdc84857e5e2b8d9aff)

**Comment by pedroSG94** [comment]
I forget add a clear in srsflvmuxer. Updated check it.
If the problem persist go to start method in that class and write a log after SrsFlvFrame frame = mFlvTagCache.take(); and post me log.

**Comment by mohsalsaleem** [comment]
A different problem, preventing mic and video to be sent. [https://gist.github.com/mohsalsaleem/ad20d2edd60d1b71ab080540d1fee291](https://gist.github.com/mohsalsaleem/ad20d2edd60d1b71ab080540d1fee291)

**Comment by pedroSG94** [comment]
I did a little refactor in rtmp module to check if you get sps and pps because i think that it is the problem.
If not, you will see "waiting for sps and pps, video packet ignored" in log in this case your device have a issue with video codec and need set sps and pps manually to it. Try with it and show me the log.

Anyway i tested today with a S6 in my job and work, with a nexus 5X too (not nexus 5 but should be similar).

Other cause could be your wifi connection. Use custom rtmp with 640X480 and 1000 video bitrate to reduce internet charge.

Let me know what server are you using. (Wowza, Red5, etc)

**Comment by mohsalsaleem** [comment]
I'm using nginx with nginx-rtmp module. 
I'm posting the log below. 
[https://gist.github.com/mohsalsaleem/2fa4b05d30201b873399085712f860fe](https://gist.github.com/mohsalsaleem/2fa4b05d30201b873399085712f860fe)

**Comment by pedroSG94** [comment]
You maybe have a problem with the encoder because your video packets have size 16(only header).
Your log:

```
06-30 15:05:18.617 1091-2532/com.pedro.rtmpstreamer I/SrsFlvMuxer: flv: h264 sps/pps sent, sps=17B, pps=8B
06-30 15:05:18.617 1091-2531/com.pedro.rtmpstreamer I/SrsFlvMuxer: worker: send frame type=9, dts=4709, size=131072B
06-30 15:05:18.618 1091-2531/com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Video, size: 41
06-30 15:05:18.618 1091-2531/com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Video, size: 16
```
Normal log:

```
06-30 12:34:40.333 26994-28444/com.pedro.rtmpstreamer I/SrsFlvMuxer: flv: h264 sps/pps sent, sps=14B, pps=8B
06-30 12:34:40.336 26994-28441/com.pedro.rtmpstreamer I/SrsFlvMuxer: worker: send frame type=9, dts=4582, size=131072B
06-30 12:34:40.336 26994-28441/com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Video, size: 38
06-30 12:34:40.337 26994-28441/com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Video, size: 8013
```

You are using color 21(FormatVideoEncoder.YUV420SEMIPLANAR) selected for library automatically. Maybe that color is not working properly in your device. Go to rtmpBuilder in preparevideo and try with:
FormatVideoEncoder.YUV420PLANAR, FormatVideoEncoder.YUV420PACKEDPLANAR or  FormatVideoEncoder.YUV420PACKEDSEMIPLANAR.
If crash is because your device don't support that color try with other.
