### ISSUE TITLE
Stream connection stop on rotating the screen to landscape mode

### ISSUE THREAD

**Issue by Rishabhsoti** [pedroSG94/rtmp-rtsp-stream-client-java#130]

**Comment by pedroSG94** [comment]
Yes. It isn't a bug, it is intentional because the plan is emulate record video of mobile apps that can't rotate activity while record video.
This should be considered like feature to develop.

**Comment by Rishabhsoti** [comment]
is there any option that we can use so that on rotation connection does not break

**Comment by pedroSG94** [comment]
The problem is that surface is destroyed when you rotate activity so you will need stop opengl and camera and restart it when surface is created. 
Theoretically you can do it modifying this class with camera1:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java
Or this if you use camera2:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java
