### ISSUE TITLE
Freezing in video

### ISSUE THREAD

**Issue by IntuitiveAppz** [pedroSG94/rtmp-rtsp-stream-client-java#133]
When we start a stream, it is freezing the video. This happens in some devices when the resolution is equal or greater than 1280x720.

rtmpCamera1.prepareVideo(720, 1280, 30, 1500x1024, false, 180)

I tried changing the bitrate and the problem continues

**Comment by pedroSG94** [comment]
What view are you using, SurfaceView, TextureView or OpenglView?
Can you tell me device models and Android API version?
Did you try with camera2 or use other view?

**Comment by rodrigommacedo** [comment]
now OpenglView, but I tested SurfaceView it and the problem occurred.

Model Device: Moto G4 Plus Android 7.0.

**Comment by pedroSG94** [comment]
Only freeze with SurfaceView?
Can you show me logcat?

**Comment by pedroSG94** [comment]
I did changes to camera1 buffer to buffer mode. This affect to rtmpCamera1 and rtspCamera1 stream if you use surfaceview or textureview.
Please get last commit and let me know if the problem is solved. If not send me a logcat

**Comment by IntuitiveAppz** [comment]
I will go test and return with feedback

**Comment by rkoshti** [comment]
it is still happeing in moto g4 plus 7.0

**Comment by pedroSG94** [comment]
@rkoshti What configuration are you using? show me your prepareVideo, prepareAudio and view used.

**Comment by muehlemann** [comment]
still happening for me on Pixel 2:
```
videoRTMP.prepareVideo(1280, 720, 30, 2000 * 1024, false, 90);
videoRTMP.prepareAudio(96 * 1024, 44100, true, false, false);
```
bitrate is in the range of (2000...4000) * 1024 and Im using a `SurfaceView`

**Comment by pedroSG94** [comment]
I can't reproduce your case with my devices. First of all I need know:
When you call startStream, the app is frozen or only preview?

Try the following things:
- Use openglview instead of surfaceview.
- Record video instead of start stream to discard encoder initialize freeze.
- Write a log per line in startStream method to know the line that freeze you app and report me the line that cause your app freeze to try fix it.
