### ISSUE TITLE
H.264 encoder

### ISSUE THREAD

**Issue by mhackeras** [pedroSG94/rtmp-rtsp-stream-client-java#138]
Hi again.. :) 
i would like to ask if it is possible to use nv12 format instead of yuv420p.. also if u have tried it already? i think for streaming its way better lighter..

**Comment by pedroSG94** [comment]
Hello,
Actually this library get frames from camera in nv21 that is like nv12 but with u and v planes reverted so you can use this format if you want, using a color conversion like I do with YV12(supported in this library too).
https://wiki.videolan.org/YUV/#I420
The problem is that I don't know how to rotate nv12 frames for now if you want use it directly without color conversion that is the only reason to add this feature(but maybe I can develop it using nv21 rotation like guide). Also maybe any video encoder doesn't support yuv420sp(nv12).

The best way to do color conversion and rotation more fast is libyuv in C++ for example or you can use LightOpenGlView or OpenGlView if you want skip all color conversion(This use OpenGl and need API18+).

Anyway add this feature and let develop choose color format and nv21 used by default is good idea for optimize speed on some devices. I will see it in more detail and if the result is good, I will add it.

**Comment by mhackeras** [comment]
hmm ok i was asking for performance improvement.. but if its like that yuv420 is way better! 
i like to stream games and i have a tons of questions ! :D also building an app on windows for streaming recording etc. if you would like to discuss more on this give me a way to contact you on private.

**Comment by pedroSG94** [comment]
You can use email: pedrossgg1994@gmail.com
