### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException getParameters failed (empty parameters)

### ISSUE THREAD

**Issue by LutfiTekin** [pedroSG94/rtmp-rtsp-stream-client-java#157]
> android.hardware.Camera.native_getParameters (Camera.java)
> android.hardware.Camera.getParameters (Camera.java:2011)
> arrow_right
> com.pedro.encoder.input.video.Camera1ApiManager$1.run (Camera1ApiManager.java:137)
> android.os.Handler.handleCallback (Handler.java:754)
> android.os.Handler.dispatchMessage (Handler.java:95)
> android.os.Looper.loop (Looper.java:163)
> android.os.HandlerThread.run (HandlerThread.java:61)

this occurs on Xiaomi Redmi Note 4 Android 7.0

**Comment by pedroSG94** [comment]
Camera1ApiManager line 137 is:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L137

According to Android documentation this error is when you call getParameters method of camera api so you are using an old library version.
Please update library version and share me full crash log to debug it. I need know line crash because getParameters is called multiple times in that class.

**Comment by LutfiTekin** [comment]
Okay I will try that

**Comment by LutfiTekin** [comment]
Sorry for the late reply. I was indeed using an old version (1.2.7) It was working on my own device normally (Xperia XZ android 8) but crashing on that phone(redmi). Upgrading fixed it.
