### ISSUE TITLE
Can this library be used to stream a textureview which is being populated by some other source and not camera?

### ISSUE THREAD

**Issue by tarunnickelfox** [pedroSG94/rtmp-rtsp-stream-client-java#160]
Hi, 

I have a texture view which is being populated by some other source. I want to stream whatever comes on that texture view to a rtmp server. Is it possible to do so using your library?

Thank you

**Comment by pedroSG94** [comment]
No by default. You need do modifications.
If you use AndroidViewFilter to replace camera source to canvas of your view it is possible.

**Comment by tarunnickelfox** [comment]
I am getting a stream from drone which can be published on SurfaceView and TextureView. I can also transform the raw h264 buffers to Yuv images. Now I need to get this to a rtmp server. How can I use your code to do so? or any other way and guidance would be appreciated.

Thank you

**Comment by pedroSG94** [comment]
You have multiple ways in this case:
- Convert frames to nv21 yuv type and stream like I do with camera1 buffer to buffer mode (using textureview or surfaceview in this library). Maybe the most easy to emulate because you have a example in this classes(I recommend you delete all code related with any openglview, no necessary in this case): https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera1.java
- Send h264 buffer directly to rtmp module. For this you need should use this method: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java#L217
- Use AndroidViewFilter to stream your textureview or surfaceview (it is the option that I commented you but maybe the most difficult and flexible because you can add more effect to stream like watermark with opengl).

**Comment by tarunnickelfox** [comment]
Thank you so much for guidance. I really appreciate you taking out time for this.
