### ISSUE TITLE
Adaptive bitrate support

### ISSUE THREAD

**Issue by EitanGoldfrad** [pedroSG94/rtmp-rtsp-stream-client-java#172]
Hey Pedro,

How does the the current implementation handles bandwidth changes? 

Do you have any plans to implement adaptive bitrate?

Love your work!

**Comment by EitanGoldfrad** [comment]
Hi Pedro,

I've created a fork of https://github.com/facebook/network-connection-class to mesure upload speed (instead of download speed) so it will be more accurate for streaming.

Would it help you if I send it to you?

**Comment by pedroSG94** [comment]
Yes, this could help me to develop this feature.
If you can share the code uploading your fork to github or share me by other way this will be good

**Comment by EitanGoldfrad** [comment]
Here you go:

https://gist.github.com/EitanGoldfrad/1fedb8cee4edf340826d771931d8928a

Let me know if there's something else I could help with.

**Comment by EitanGoldfrad** [comment]
Ya, it's practically the same.

**Comment by pedroSG94** [comment]
I uploaded your library to this project with a modification to get upload bandwidth on realtime instead of an enum depend bandwidth interval. To implement adaptative bitrate with it should be simple. My algorithm idea:
If you put some bitrate and the bandwidth is significantly less than bitrate used you can reduce video bitrate with the method of my library if the bandwidth is similar to bitrate used then you can increase bandwidth.
I will try do an implementation of it. 
Commit: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/e556a622ca5a56bbbb23b9dcb268bdfa37c03b27

**Comment by EitanGoldfrad** [comment]
Sounds good!

I think you need to adjust the bitrate gradually so you don't have spikes in quality.
Also make sure you only change the bitrate between a min and max threshold based on user chosen quality.

By the way: do you have an indication of the number of frame that are waiting in the publish buffer?

**Comment by pedroSG94** [comment]
I did an implementation of this but no limit of bitrate depend of your resolution. You will get always max bandwidth. Simply need add this code to your callback of quality:
```java
connectionClassManager.register(new ConnectionClassManager.ConnectionClassStateChangeListener() {
      @Override
      public void onBandwidthStateChange(double bandwidth) {
        AdapterBitrateParser.parseBitrate(rtmpCamera1.getBitrate(), bandwidth, new AdapterBitrateParser.Callback() {
          @Override
          public void onNewBitrate(int bitrate) {
            rtmpCamera1.setVideoBitrateOnFly(bitrate);
          }
        });
      }
    });
```
The rest of code is the same that you used with the library that you shared. Instance in onCreate method, startSample before startStream and stopSample before stopStream.
The question to implement max bitrate with a resolution is: An arbitrary bitrate selected by me or let user select the max? What do you think is the best option?

I have the number of frames in queue in rtmp but no in rtsp (I need develop a method to get it because in rtsp is not a queue it is an array that if you set more frames that size replace frame in the oldest position.

**Comment by EitanGoldfrad** [comment]
I think that you can set the default Max bitrate and Min bitrate to be some MULTIPLIER * selectedBitrate.

For example: if the user selected 1000kb the Max can be 1.5 * 1000kb and the min bitrate 0.5* 1000kb.

Also I would change the bitrate only if it changed more than a certain threshold (at least 50kb-100kb)

Alternatively you can see this post for bitrate depending on resoluion : https://teradek.com/blogs/articles/what-is-the-optimal-bitrate-for-your-resolution

Regarding the frame buffer:
You can implement another important aspect of adaptive streaming if you start dropping frames if the frame buffer gets close to a certain limit and shut off the stream entirely if it's above the limit for a certain amount of time.

**Comment by pedroSG94** [comment]
I was discuss it with a friend and maybe the result will be an arbitrary max and mix depend resolution using your link and let user modify it with a method.
About drop frames. The library already drop frames but close stream automatically if you drop frame so much time I don't like it. Let user know it could be good and then let his decide it.

**Comment by EitanGoldfrad** [comment]
Ok, sounds good.

Let me know if you need any help

**Comment by EitanGoldfrad** [comment]
Hi @pedroSG94 ,

Has this feature been implemented in one of the branches?

Regards

**Comment by pedroSG94** [comment]
Yes. It is implemented in master branch, use wiki to know how to use it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Adaptative-video-bitrate.

**Comment by pedroSG94** [comment]
Yes. It increase bitrate or decrease it with a limit if you select a limit (See optional section in wiki).
