### ISSUE TITLE
Support for Ice cream Sandwitch

### ISSUE THREAD

**Issue by ellu15** [pedroSG94/rtmp-rtsp-stream-client-java#186]
Hello, 

Is there any change or version that we can use this as to support API 15 or Ice cream sandwitch ( 4.0.4 ) 

Thanks

**Comment by pedroSG94** [comment]
Unfortunately I haven't any version for API 15. Android encoding is only available for API16+:
https://developer.android.com/reference/android/media/MediaCodec 
You can try replace encoding with some software encoding for example x264 by videolan but I can't help you with it because my experience in C/C++ is really low.
https://www.videolan.org/developers/x264.html
