### ISSUE TITLE
How to use RTMPS?

### ISSUE THREAD

**Issue by denebchorny** [pedroSG94/rtmp-rtsp-stream-client-java#191]
I am testing the demo app but using a RTMPS shows me a connection error. We used the same url in an IOS project an it works fine. 

What do I need todo to run a RTMPS in my project with the library?

PD: my RTMPS doenst use an user and password. But if it is mandatory ust tell me

**Comment by pedroSG94** [comment]
You only need write rtmps instead of rtmp in the url like:
- normal RTMP: rtmp://ip:port/app/streamname
-secure RTMP(RTMPS): rtmps://ip:port/app/streamname

You have an example in strartStream header method:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L391

If the error persist share me url, ios streamer library, string reason of connection error and a logcat.

**Comment by denebchorny** [comment]
Thank you sir. I am so sorry. The issue was the port. I was using a wrong one. The library is wowwww so niceeee
