### ISSUE TITLE
server Call Back

### ISSUE THREAD

**Issue by padmanaban01** [pedroSG94/rtmp-rtsp-stream-client-java#21]
Hi 
How can we get the status,  when the server disconnected the stream,
for example when we are in live broadcast due to some network error the stream to server is lost in that scenario how can we identify the status of the stream,
also we need to reconnect the stream in specific interval.
we check that on on the RtmpBuilder class always shows the streaming is   true.

**Comment by pedroSG94** [comment]
I did a commit for RTMP. You will be notified in onConnectionFailed callback on both RTMP and RTSP if you lose connection with server.

**Comment by padmanaban01** [comment]
ya the connection failed is their, but once we start the streaming, when we stop the server or close the port, how can we get the call back status.

**Comment by pedroSG94** [comment]
I don't understand the question.
Do you want know when the server is down while streaming or status of the stream when you reconnect to server?
If you start a stream and close the server you will be notified in the callback onConnectionFailed.
Maybe do you want a status code of the server response? (404, 401, 500, etc).

**Comment by padmanaban01** [comment]
@Override
  public void onConnectionFailedRtmp() {
        runOnUiThread(new Runnable() {
      @Override
      public void run() {
        Toast.makeText(RtmpFromFileActivity.this, "Connection failed", Toast.LENGTH_SHORT).show();
        rtmpBuilderFromFile.stopStream();
        button.setText(getResources().getString(R.string.start_button));
      }
    });
  }
but in this above function we cannot get the status while streaming when the server is down,

**Comment by pedroSG94** [comment]
Ok, now should be fixed. I tested start stream and shutdown server while stream and work with my local server.

**Comment by padmanaban01** [comment]
i tried the latest code but still the issue their, can u help me to clarify the issue.

**Comment by pedroSG94** [comment]
Yes, I need fix it.

**Comment by pedroSG94** [comment]
I was testing the firewall connection if I disable a port but that is imposible to implement.
If you do a streaming and then you close the port while stream all continue normally because you did the connection before you closed the port.
You can test it with this:
- Connect to a remote server stream.
- Close port in client side firewall.
- Use VLC to open stream with other net without port closed.
I did it with my wifi like firewall with port closed and 3G data to get stream with VLC in other device and I can get stream.
You can test too if you go to your server and see that the server receive packets.

**Comment by padmanaban01** [comment]
ok thanks for your timely response
