### ISSUE TITLE
Different quaility for streaming and recording

### ISSUE THREAD

**Issue by about-prog** [pedroSG94/rtmp-rtsp-stream-client-java#228]
Hello!
I use adaptive bitrate streaming. And quality of stream is same as on recording. Is it possible to have on record on phone better quality (more bitrate) then on stream?

**Comment by pedroSG94** [comment]
No because I use same encoder to record and stream. If you want do it you need duplicate videoencoder and use a different encoder for stream and video record. Anyway you can stream with max resolution supported by your device if you use camera2 (camera1 only support 1080 or below). For example I can stream 4k with samsung s7

**Comment by about-prog** [comment]
Thanks for response!
The thing is: in my case there may be many streams in bad network areas and I want for streams use adaptive bitrate (so even if network is weak, it's something visible) and save videos on phone for later in good quality (so if something important happend - it's possible to copy from phone to check in good quailty).

Thanks for advice. Is it the code related to Camera1Base and getH264Data?

**Comment by pedroSG94** [comment]
You should duplicate this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L55
And use one streaming and other recording.
