### ISSUE TITLE
Streaming without preview ( running app in background?)

### ISSUE THREAD

**Issue by deeepakpatil** [pedroSG94/rtmp-rtsp-stream-client-java#23]
Hi,
Could you please implement streaming without preview ?
A radio button / check box can be added to toggle On/OFF preview.

A] Intent is to start streaming on boot, with locked screen (i.e. without preview).
B] Something like linux watchdog / crontab can be used to restart the app at regular interval if not running.
C] **Idea is to make it remote streaming device, which can run without supervision.**

*Not sure how to handle android notifications. I would prefer running this app in background.

This feature will significantly boost the utility of this app.

**Comment by pedroSG94** [comment]
Im not sure if you can do it.

But if you can, only is posible with surface mode encoding with camera API2 because camera API1 need a active surfaceview, textureview or surfacetexture.

If you want test go Camera2APIManager in encoder module and delete the surface from surfaceview in line 51. Then use RTMP or RTSP builder that extends from BuilderSurfaceModeBase class. You need API21 for this.

Other way is use the normal builder and using this android class to create a windows that you can use while your app is in background:
https://developer.android.com/reference/android/view/WindowManager.html

**Comment by pedroSG94** [comment]
Streaming in background is now possible with RtmpBuilderSurfaceMode or RtmpBuilderSurfaceMode using constructor with context instead of surfaceview.
Remember that this mode is under develop and rtmp in this mode has some problems. I recomend you use rtsp (working on Sansumg S7 for me perfectly).
Added in commit: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/7a849bc1e56833aa9d132d3a15f842ff2da0c5f3

**Comment by Shanmugamsundarrajan** [comment]
My requirement is to do RTSP Streaming in back ground (Service),   
can you please share the code,

**Comment by jsraffi** [comment]
Hi, there, Is RTMP streaming in background fixed?
