### ISSUE TITLE
Not working with google Vision API

### ISSUE THREAD

**Issue by divyashamar** [pedroSG94/rtmp-rtsp-stream-client-java#236]
hello,
I am trying to deal with wowza streaming and face-detection in parallel task. In my project I have done google Face Detection (Vision API) not trying to send data over network using wowza server.

Please suggest how I can make this.

**Comment by pedroSG94** [comment]
I don't know how work google vision api and I haven't plan to add this dependency to my project. Fow now, you can try use native android face detection but it is experimental. I recommend you use camera1 because camera2 no work fine (This is experimental, maybe no work).
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L120

If you really need use google vision api try implement it in this classes:
Camera1:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java
Camera2:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java
