### ISSUE TITLE
Samsung Galaxy S5 streaming problem to Wowza

### ISSUE THREAD

**Issue by about-prog** [pedroSG94/rtmp-rtsp-stream-client-java#244]
Hi!
Ater update to latest version I have a problem with streaming from Samsung Galaxy S5.
In player I can only hear sound but no video.
And if adaptive bitrate is enabled there is a list of bitrates (Kbps):
988, 152, 1007, 1105, 209, 140, 1055, 1109, 182, 1114, 178, 140, 1082, 1115, 169, 1116, 167, 1118, 166, 1119, 165, 143, 1100, 1119, 161, 143, 1102, 143, 1103, 139
So almost every second bitrate jumps from high to very low. Checked on two galaxy s5 in different parts of the world - same.
I used these settings:
AdapterBitrateParser.maxVideoBitrate = 1500;
AdapterBitrateParser.DELAY = 1000;

**Comment by pedroSG94** [comment]
reduce difference to change jump size:
```java
AdapterBitrateParser.DIFFERENCE = 100;
```
About video player. Try use VLC to reproduce stream. Also make sure that you open rtmp or rtsp endpoint (depend of your stream protocol) to avoid transcoding.
Also you can see bitrate stats received by wowza to know if video is received. My recomendation for it is use 3000 * 1000 video bitrate (no adaptative) because the bitrate difference with only audio or video and audio is high and you can see the different easy.
If the problem persists let me know protocol, mode (camera1, fromfile) and constructor used.

**Comment by about-prog** [comment]
On wowza it shows bitrate around 130Kbits/s. No transcoding is used.

Here is my code:
        rtmpCamera1.prepareAudio();
        uploadBandwidthSampler.startSampling();
        rtmpCamera1.prepareVideo(640, 480, 30, 1200 * 1024, false, 2, CameraHelper.getCameraOrientation(this));
        rtmpCamera1.startStream(rtmpUrl);
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd_HH:mm:ss", Locale.getDefault());
        currentDateAndTime = sdf.format(new Date());
        try {
            if (!folder.exists()) {
                folder.mkdir();
            }
            rtmpCamera1.startRecord(folder.getAbsolutePath() + "/" + currentDateAndTime + ".mp4");
        } catch (IOException e) {
            rtmpCamera1.stopRecord();
            Toast.makeText(this, e.getMessage(), Toast.LENGTH_SHORT).show();
        }

And I've just find out that if I disable recording, then stream is working.

**Comment by about-prog** [comment]
Actually without recording it's much better, but still sometimes it's just audio. Though, most of the times it's fine

**Comment by pedroSG94** [comment]
startRecord at same time that startStream could be the error. I will check it.
