### ISSUE TITLE
Adding Streaming id and Date Time to Capturing in video

### ISSUE THREAD

**Issue by padmanaban01** [pedroSG94/rtmp-rtsp-stream-client-java#25]
How can we Add Streaming id and Date Time to the video as a over layer, Also If it is possible to record the feed that we are streaming in the local storage,

**Comment by pedroSG94** [comment]
Implement record should be easy with [MediaMuxer](https://developer.android.com/reference/android/media/MediaMuxer.html) android class because you only need a getter for mediaformat of video and audio encoders and use h264 and aac callbacks for send data to the mediamuxer.

I'm not sure what is Id stream (Maybe stream name of the endpoint?) but add a watermark is possible if you do a post process video and add it with opengl. In real time you need use surface mode stream (under develop it have some problems for now) and modify it for use opengl and add a watermark.

Record in local storage could be added for me but add a watermark in real time not for now. Maybe in the future, not discarded of all.

**Comment by pedroSG94** [comment]
Record mp4 file was added in the last commit:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/22f2f27c17a47e9cc1c9b740d28c404e8a7892ce
