### ISSUE TITLE
Rtmp from file lag

### ISSUE THREAD

**Issue by BluestarCo** [pedroSG94/rtmp-rtsp-stream-client-java#250]
hi mr pedro
when i stream from mp4 (file size 80mb)
audio is play slowly and not sync by video
and video play with lag

**Comment by pedroSG94** [comment]
Hi,
First try stream with that device using other mode with camera1 or camera2 to discard encoder problems sync. 
I think the problem is that your device decode more slowly than video fps. Try with a good device or with other file with low resolution and 30fps or less. Also you have a method to resync file:
```java
rtmpFromFile.reSyncFile();
```
Can you tell me device model used, Android API, video fps and video resolution?

**Comment by BluestarCo** [comment]
samsung galaxy s8+ ,api 27, fps 30, 720p

**Comment by pedroSG94** [comment]
I'm looking reason but no result for now. I use s7 and s6 but work fine with this video:
http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
Can you share me your video? maybe the problem is video format or some configuration in video.

**Comment by pedroSG94** [comment]
For now you only can send video without transform. You can set a filter to video but I think that it isnt a good solution for you. Anyway you can try it.
Use opengl mode:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/FromFileBase.java#L75

Add rotation filter:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L221

It is a new feature. I will add video rotation in fromfile mode in the future.

**Comment by pedroSG94** [comment]
I did rotation feature in this commit:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/663ebab0e135ec5b4e7a83ae176214f28bad2997
