### ISSUE TITLE
OpenGL view with keepAspectRatio = true has an artifact on cliped areas

### ISSUE THREAD

**Issue by andrewBatutin** [pedroSG94/rtmp-rtsp-stream-client-java#251]
OS: Android 7.1.1 SDK version - 1.4.2
Device: Moto E (4) Plus

Choose any video resolution different from 1280x720 and 768x432 and **OpenGlView** with **app:keepAspectRatio="true"** will show artifacts on clipped areas [
![screenshot_20181026-115912](https://user-images.githubusercontent.com/8652454/48498639-54e9eb00-e83f-11e8-9ee6-3887ab3dd6d3.png)
](url)

this behavior is reproducible only on this Motorola device

**Comment by pedroSG94** [comment]
If you only cna reproduce it I will need your help to fix it.
I think the problem is a bad glclearcolor.
Clone my app and try this:
In this line: 
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/ScreenRender.java#L80
Add this:
```java
    GLES20.glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
    GLES20.glClear(GLES20.GL_DEPTH_BUFFER_BIT | GLES20.GL_COLOR_BUFFER_BIT);
```

**Comment by andrewBatutin** [comment]
will do

**Comment by andrewBatutin** [comment]
clear color helped
