### ISSUE TITLE
Network limited

### ISSUE THREAD

**Issue by nicfedor** [pedroSG94/rtmp-rtsp-stream-client-java#26]
looks like your library cannot use the full speed of available network connection. I tried Wowza gocoder and it fills my connection to the top providing great quality. Your library cannot make upload faster than 80-100 kB/s.

**Comment by pedroSG94** [comment]
Did you tried use more video bitrate or only tried with default method?

**Comment by nicfedor** [comment]
Yes, I tried. If I set bitrate more than 400 kbit/s, then video on player become lagging because it didn't receive enough frames/s because library can't make it faster than 50 kB/s (400kbit/s).

**Comment by pedroSG94** [comment]
I think this is no library problem because I tried multiples times with 3000kbits and work fine.
vlc screenshoot with server in local net with 2500kbs video bitrate in custom rtmp activity:
![captura de pantalla de 2017-07-30 11-27-14](https://user-images.githubusercontent.com/17556876/28752217-5fe079aa-751a-11e7-9aa7-b9892453f085.png)

**Comment by nicfedor** [comment]
Yep. You right. I tried on other device and it streams on full speed.

**Comment by pedroSG94** [comment]
Can you tell me device model and Android API for future issues? Maybe the problem is the network card and i want know that hardware model.

**Comment by nicfedor** [comment]
My smartphone Huawei Honor 5A (lyo-l21) and it can't do more than 50-80 kb/c upload speed. But my tab Huawei T1 10 LTE can stream on maximum speed on the same wi-fi network.

**Comment by pedroSG94** [comment]
Android version no problem because I tested in a moto g with same version and work, so I think could be a wifi device problem. Maybe your device is using wifi b instace of g or n. Unfortunately I cant help you with that because I never see this before and I can't reproduce :(
Other reason could be that mediacodec class of Android is not working with the bitrate properly in that device but this is more difficult.

**Comment by nicfedor** [comment]
Looks like it really depends on what speed streaming was connected to the network, because I don't see speed more than those at the first seconds of the stream. So sometimes my tab also stuck on low speed and can't increase speed.

**Comment by pedroSG94** [comment]
That could be the reason, anyway you can change video bitrate on fly. To do it use custom activity and while you are streaming change video bitrate and for apply close the options menu.

**Comment by nicfedor** [comment]
Yeah. I do it. Works fine. Is there any possibility to change a resolution of the stream on the fly or I have to stop the stream and reinitiate it?

**Comment by pedroSG94** [comment]
No, you can't do it on fly.
