### ISSUE TITLE
SamSung device, OpenGL set image filter then display is black

### ISSUE THREAD

**Issue by hqthong10** [pedroSG94/rtmp-rtsp-stream-client-java#280]
With SamSung device, rtmpCamera1.getGlInterface().setFilter( imageFilter) display is normal. Then rtmpCamera1.getGlInterface().setFilter(new NoFilterRender()) display is normal. Continue rtmpCamera1.getGlInterface().setFilter( imageFilter) display is black.

**Comment by pedroSG94** [comment]
When you set bitmap to filter opengl create a texture and then I'm doing a bitmap recycle. After change filter bitmap texture is released so you need recreate bitmap and set it to filter before setFilter.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L284
As you can see. I'm creating bitmap always before setFilter.

**Comment by pedroSG94** [comment]
Object filter (ImageObjectFilterRender, GifObjectFilterRender, SurfaceFilterRender and TextObjectFilterRender) dissapear when you start stream or record (I need change it). For now, you should recreate this filter after start stream or record.

**Comment by hqthong10** [comment]
I know that, so I only executed filter when streamed. Oppo, Zenfone, Xiaomi devices work well, but Samsung, huawei devices not good. As well as a gif image will flash black after a life cycle.

**Comment by pedroSG94** [comment]
I will check it with my Samsung S7.
Can you tell me Samsung and Huawei models that is not working?

**Comment by hqthong10** [comment]
I run on Samsung J7 Pro, Samsung J4, HUAWEI nova 3i (INE-LX2), Sumsung note 8. I think all samsung devices. 
with the above devices, filter surface will stop after a few seconds of play. Other devices run very well.

**Comment by hqthong10** [comment]
ok, thank you for help me. This library is very good.

**Comment by miwaniec** [comment]
Hi @pedroSG94 
I had the same information from my user and today tried to analyze this problem.
Probably the problem is not in your library, it is a known OpenGL problem in some devices. Maybe one of this information will help you.
https://stackoverflow.com/questions/39589247/opengl-es-2-0-draw-bitmap-overlay-on-video
https://stackoverflow.com/questions/13183121/android-opengl-es-2-not-working-on-all-devices
https://stackoverflow.com/questions/20710027/android-opengl-es-2-0-black-textures-on-some-devices

I found the same device as my user - Samsung Galaxy Device S7 with android 7.0 and it works correctly. After upgrade to android 8.0 has stopped working (official device update).

I tested with demo app, version 1.5.3, OpenGl RTMP activity. What happens exactly:
1. Start streaming/recording
2. Add image (still ok)
3. Add image again (or remove the filter and add image) causes that the image is displayed for black. Size is exactly the same.
4. After stop streaming/recording, all works ok.

The same effect is with text and gif, but with gif only one frame is black (probably first).
Without streaming/recording I can add and delete an image without end and it's always ok. Others filters also works ok. The same effect for RtmpCamera1 and RtmpCamera2.
I don't have knowledge about OpenGl, but I think something is wrong with the texture. You use GL_TEXTURE5 for all this (image, text, first frame of gif).
I hope this information will be helpful. Solving this problem really is needed!
If you need more test, this week I have a device and some time.

**Comment by pedroSG94** [comment]
@miwaniec 
I can reproduce the error. I will try fix it. 
Thank for links and info.

**Comment by pedroSG94** [comment]
Fixed, this is working on S7 with Android 8.0. I haven't more devices so if you can test in others devices to confirm that work I will be grateful.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/e41219b024240f2692e85f1517c629ab3597c823

**Comment by pedroSG94** [comment]
Fixed: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/68893810dfa2feec1b227d2b77efa54bc4cd1598

**Comment by miwaniec** [comment]
For image works ok - can you make version 1.5.4 with this commit? I think most of user use image.
When I add a gif, the effect is the same. The first frame is black and add image has the same effect - black.

**Comment by pedroSG94** [comment]
I will fix gif and update all join.

**Comment by miwaniec** [comment]
@pedroSG94 
During recording everything is ok.
Now is a problem with start recording with added image/gif. When you start, black texture stays on video.

**Comment by pedroSG94** [comment]
Fixed: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/86f74987ac56da334e6df2ce09ed53e6c02ffd7c
Version updated to 1.5.5.
I have plan to change opengl's textures lifecycle to keep this when you start record or stream for now it is working like in old versions.

**Comment by miwaniec** [comment]
Good plan!
For image is good, but for gif sometimes when I start or stop recording is fatal error (index is out of range).
`java.lang.IllegalArgumentException: length - offset < n < needed
        at android.opengl.GLES20.glDeleteTextures(Native Method)
        at com.pedro.encoder.input.gl.render.filters.object.BaseObjectFilterRender$1.run(BaseObjectFilterRender.java:134)`

Sorry for the accuracy. I don't need gif support, but when I got error I prefer to describe it.

**Comment by pedroSG94** [comment]
wow. This is not my day XD.
Fixed gif error and version updated: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/cf834c9c982fe55a6d856631153bac892bda8db7
Now, all should work fine. Thanks for report errors and help me test it!

**Comment by miwaniec** [comment]
I can't screw up :) Works well, thanks 👍 
The issue to close.

**Comment by haseeb362-amoxt** [comment]
> Ah ok, the problem is this:
> #222
> I tried fix it but I can't find the solution. Are you rendering surface with MediaPlayer?
> I was looking error reason but MediaPlayer never throw any error or event when video stop.
> You can try replace MediaPlayer with other player like VLC.

This definitely not an issue with MediaPlayer, because I used a second camera to display in the SurfaceFilterRender and it works fine while not streaming but has issues as soon as I stream, by issues I mean to play for a few seconds.
