### ISSUE TITLE
[Question] Do you plan to support SRT?

### ISSUE THREAD

**Issue by andrewBatutin** [pedroSG94/rtmp-rtsp-stream-client-java#282]
Do you plan to support SRT?

https://www.srtalliance.org/

It's a UDP low-latency transport that a lot of enterprise streamers have and love. Do you plan to add it to the lib?

**Comment by pedroSG94** [comment]
I don't want add C/C++ code to the project because I'm not really good coding in this language and maintain code will be difficult for me. Also my initial purpose in this project is use only JAVA because all Android developer know this language and they can understand, modify and contribute to the project more easly.
This is a interesting implementation but I can't find SRT documentation to reproduce protocol in JAVA code(connection negotiation, packet documentation, etc). If I try read all github code and understand it. I will need so much time and this is no viable.

If you find SRT documentation I can try it but, for now, other protocols like HLS or DASH is more interesting for me.

**Comment by pedroSG94** [comment]
This could be a solution but this need time. I think this isn't a feature for the near future.
I will do a try with this:
https://github.com/Haivision/srt/blob/2f894b4cf956408958122c3bfb69368ef8042ce7/docs/Android/Compiling.md
