### ISSUE TITLE
Not an issue but just some questions 

### ISSUE THREAD

**Issue by moster67** [pedroSG94/rtmp-rtsp-stream-client-java#29]
This is not an issue but just some questions:

-The rotation is bugging me when VLC (desktop) shows the stream with the wrong rotation. This seems to be limited to Portrait mode. If I understand correctly, mediacodec rotation = hardware rotation and if hardware rotation is set to true, the (software) rotation values are ignored. Is this correct? What is the exact purpose of hardware rotation? 

-Is there a way to avoid start streaming again when switching cameras. Using my Samsung s8 the rotation changes when I see it in VLC after switching cameras. Maybe this is not possible to do on the fly because the server needs to know it beforehand? But maybe it is possible since the bitrate can be changed on the fly?

-having the possibility to change the bitrate on the fly, how would it be possible to adapt the bitrate automatically? Can I somehow get the current speed of the upload connection? Or do I need to get it from the server and than set the new bitrate value?

Thanks for this superb library.

**Comment by moster67** [comment]
Also, is it possible to invert the image to avoid the mirror-effect.

**Comment by pedroSG94** [comment]
1- Hardware rotation purpuse is do the same that software rotation but with the mediacodec (that should be more efficient that software using a java method) but somes device ignore this, that is the reason because I did software rotation.

2- The rotation in your stream changes because frontal camera has different orientation that back camera, normally 180º rotation is the different. You can implement a simple boolean variable to control what camera are you using and use YUVUtil class to rotate the image 180º when you use frontal camera. The stream never stop, you can see a black screen because in that moment camera is closed and reopened to switch camera. You can check it because audio continue in that moment.

3- Adapt bitrate automatically is pretty difiicult, I tried do it in the past but I couldn't find a good example for read upload speed connection.

4- This is possible with libyuv library. I can't found a pure java solution :(

**Comment by pedroSG94** [comment]
Mirror effect added to YUVUtil class :D
If you want test go to This line in the project:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/a75faa93311d201ac81be467c1b681cfd184f180/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L192

replace with this line:

`getCameraData.inputNv21Data(YUVUtil.mirrorNV21(data, width, height));`

In that line you can apply rotation for frontal camera too.

**Comment by moster67** [comment]
Thx. I will try that.
For the rotation, , should I use the YUVUtil.rotateNV21 method?

`getCameraData.inputNv21Data(YUVUtil.rotateNV21(data, width, height, 90));`

**Comment by moster67** [comment]
For adaptive bitrate, I found this on SO:
https://stackoverflow.com/questions/43255500/rtmp-adaptive-bitrate-algorithm

But according to the poster it does not work :(

**Comment by moster67** [comment]
Mirror effect works :) Thx.

**Comment by moster67** [comment]
For rotation when switching from back to front camera, this code works fine:
`  @Override
  public void onPreviewFrame(byte[] data, Camera camera) {
    if (fpsController.fpsIsValid()) {
      if (imageFormat == ImageFormat.YV12) {
        getCameraData.inputYv12Data(data);
      } else if (imageFormat == ImageFormat.NV21) {
        if (cameraSelect == 0) {
          Log.i("B4A", "camera is back " + cameraSelect);
          getCameraData.inputNv21Data(data);
        }else {
        Log.i("B4A", "camera is front " + cameraSelect);
//        getCameraData.inputNv21Data(YUVUtil.mirrorNV21(data, width, height)); //to test
            getCameraData.inputNv21Data(YUVUtil.rotateNV21(data, width, height, 180));
          }
      }
    }
  }`

**Comment by pedroSG94** [comment]
Stackoverflow code don't look usable.
He try change bitrate using cache video frame, that idea could be insteresting but I'm not sure if it will work.

**Comment by rcvangemert** [comment]
Hi, Can we stream direct to a rtsp client like VLC or must we go via a server? I am looking for a p2p solution. Thanks

**Comment by pedroSG94** [comment]
No, you can't do it with this library. You need a server

**Comment by rcvangemert** [comment]
thanks
