### ISSUE TITLE
How to draw a cutout or hole on the camera's opengl view?

### ISSUE THREAD

**Issue by troy-lamerton** [pedroSG94/rtmp-rtsp-stream-client-java#290]
I need to crop the camera view to a circle shape.

I tried using a surface view and overriding `dispatchDraw(Canvas c)`, which worked. However it does not work when placed on top of another surface view.

So now I am using an OpenGlView and trying to figure out how to crop the display to a circle?

I assume this should be done with a filter, but I have no idea where to start.

**Comment by pedroSG94** [comment]
I assume that only preview should be circular right?
In this case you need modify so much the library because filters are developed to apply in stream result and preview.
I this case I recommend you create a view with a circular shape and overlay my stream view.
- Clone my project.

- Copy this class:
```java
package com.pedro.rtpstreamer.defaultexample;

import android.annotation.TargetApi;
import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.PorterDuff;
import android.graphics.PorterDuffXfermode;
import android.graphics.RectF;
import android.os.Build;
import android.util.AttributeSet;
import android.widget.LinearLayout;

/**
 * Created by hiren on 10/01/16.
 */
public class CircleOverlayView extends LinearLayout {
  private Bitmap bitmap;

  public CircleOverlayView(Context context) {
    super(context);
  }

  public CircleOverlayView(Context context, AttributeSet attrs) {
    super(context, attrs);
  }

  public CircleOverlayView(Context context, AttributeSet attrs, int defStyleAttr) {
    super(context, attrs, defStyleAttr);
  }

  @TargetApi(Build.VERSION_CODES.LOLLIPOP)
  public CircleOverlayView(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
    super(context, attrs, defStyleAttr, defStyleRes);
  }

  @Override
  protected void dispatchDraw(Canvas canvas) {
    super.dispatchDraw(canvas);

    if (bitmap == null) {
      createWindowFrame();
    }
    canvas.drawBitmap(bitmap, 0, 0, null);
  }

  protected void createWindowFrame() {
    bitmap = Bitmap.createBitmap(getWidth(), getHeight(), Bitmap.Config.ARGB_8888);
    Canvas osCanvas = new Canvas(bitmap);

    RectF outerRectangle = new RectF(0, 0, getWidth(), getHeight());

    Paint paint = new Paint();
    paint.setColor(Color.RED);  //external circle color
    osCanvas.drawRect(outerRectangle, paint);

    paint.setColor(Color.TRANSPARENT);
    paint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.SRC_OUT));
    float centerX = getWidth() / 2;
    float centerY = getHeight() / 2;
    float radius = 400; //in px
    osCanvas.drawCircle(centerX, centerY, radius, paint);
  }

  @Override
  public boolean isInEditMode() {
    return true;
  }

  @Override
  protected void onLayout(boolean changed, int l, int t, int r, int b) {
    super.onLayout(changed, l, t, r, b);
    bitmap = null;
  }
}

```
Go to layout xml and replace:
```xml
<com.pedro.rtplibrary.view.OpenGlView
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:id="@+id/surfaceView"
      app:keepAspectRatio="false"
      app:AAEnabled="false"
      app:numFilters="1"
      app:isFlipHorizontal="false"
      app:isFlipVertical="false"
      />
```
To:
```xml
<RelativeLayout
      android:layout_width="800px"
      android:layout_height="800px"
      android:layout_centerInParent="true"
      >
  <com.pedro.rtplibrary.view.OpenGlView
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:id="@+id/surfaceView"
      />
  <com.pedro.rtpstreamer.defaultexample.CircleOverlayView
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      />
  </RelativeLayout>
```

Circle view source:
https://stackoverflow.com/questions/19947835/android-canvas-draw-transparent-circle-on-image

Result:
![screenshot_20190201-104811_rtmp-rtsp streamer](https://user-images.githubusercontent.com/17556876/52115463-fbf44c80-260e-11e9-9ad7-b6203af27276.jpg)

**Comment by milren** [comment]
Thank you. Maybe I know what to do.



------------------ 原始邮件 ------------------
发件人: "Pedro Sánchez"<notifications@github.com>;
发送时间: 2019年2月1日(星期五) 下午5:49
收件人: "pedroSG94/rtmp-rtsp-stream-client-java"<rtmp-rtsp-stream-client-java@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [pedroSG94/rtmp-rtsp-stream-client-java] How to draw a cutout orhole on the camera's opengl view? (#290)




I assume that only preview should be circular right?
 In this case you need modify so much the library because filters are developed to apply in stream result and preview.
 I this case I recommend you create a view with a circular shape and overlay my stream view.
  
 
Clone my project.
 
 
 
Copy this class:
 
  package com.pedro.rtpstreamer.defaultexample; import android.annotation.TargetApi; import android.content.Context; import android.graphics.Bitmap; import android.graphics.Canvas; import android.graphics.Color; import android.graphics.Paint; import android.graphics.PorterDuff; import android.graphics.PorterDuffXfermode; import android.graphics.RectF; import android.os.Build; import android.util.AttributeSet; import android.widget.LinearLayout; /**  * Created by hiren on 10/01/16.  */ public class CircleOverlayView extends LinearLayout {   private Bitmap bitmap;   public CircleOverlayView(Context context) {     super(context);   }   public CircleOverlayView(Context context, AttributeSet attrs) {     super(context, attrs);   }   public CircleOverlayView(Context context, AttributeSet attrs, int defStyleAttr) {     super(context, attrs, defStyleAttr);   }   @TargetApi(Build.VERSION_CODES.LOLLIPOP)   public CircleOverlayView(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {     super(context, attrs, defStyleAttr, defStyleRes);   }   @Override   protected void dispatchDraw(Canvas canvas) {     super.dispatchDraw(canvas);     if (bitmap == null) {       createWindowFrame();     }     canvas.drawBitmap(bitmap, 0, 0, null);   }   protected void createWindowFrame() {     bitmap = Bitmap.createBitmap(getWidth(), getHeight(), Bitmap.Config.ARGB_8888);     Canvas osCanvas = new Canvas(bitmap);     RectF outerRectangle = new RectF(0, 0, getWidth(), getHeight());     Paint paint = new Paint();     paint.setColor(Color.RED);  //external circle color     osCanvas.drawRect(outerRectangle, paint);     paint.setColor(Color.TRANSPARENT);     paint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.SRC_OUT));     float centerX = getWidth() / 2;     float centerY = getHeight() / 2;     float radius = 400; //in px     osCanvas.drawCircle(centerX, centerY, radius, paint);   }   @Override   public boolean isInEditMode() {     return true;   }   @Override   protected void onLayout(boolean changed, int l, int t, int r, int b) {     super.onLayout(changed, l, t, r, b);     bitmap = null;   } } 
 
Go to layout xml and replace:
 <com.pedro.rtplibrary.view.OpenGlView       android:layout_width="match_parent"       android:layout_height="match_parent"       android:id="@+id/surfaceView"       app:keepAspectRatio="false"       app:AAEnabled="false"       app:numFilters="1"       app:isFlipHorizontal="false"       app:isFlipVertical="false"       />
 
To:
 <RelativeLayout       android:layout_width="800px"       android:layout_height="800px"       android:layout_centerInParent="true"       >   <com.pedro.rtplibrary.view.OpenGlView       android:layout_width="match_parent"       android:layout_height="match_parent"       android:id="@+id/surfaceView"       />   <com.pedro.rtpstreamer.defaultexample.CircleOverlayView       android:layout_width="match_parent"       android:layout_height="match_parent"       />   </RelativeLayout>
 
Circle view source:
 https://stackoverflow.com/questions/19947835/android-canvas-draw-transparent-circle-on-image
 
Result:

**Comment by pedroSG94** [comment]
I did a circle filter but for now I don't know how to set transparent color for the crop place.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/fa35c97f8eae3706d4ced9bf86b3a93ea0b1c64b
I thought that replace glClearColor method with alpha = 0 should work but it is not working...
I will try find the solution.

**Comment by troy-lamerton** [comment]
That circle filter is helpful. I got the preview working by calling a callback with the byte[] of the current frame in `onPreviewFrame`. Then it was just a matter of byte[] -> Bitmap, and cropping the canvas when rendering to my surfaceView.

**Comment by troy-lamerton** [comment]
I found a way to do it by setting the outline of the camera view to a circle. Turns out this method can be used to crop and view to a circle.

This is the Kotlin code I use to do it. Note that I crop a little extra to allow room for another view to show a border.
```
class CircleGlView : LightOpenGlView {

    constructor(context: Context) : super(context)
    constructor(context: Context, attrs: AttributeSet) : super(context, attrs)

    private val circleOutlineProvider = object : ViewOutlineProvider() {
        override fun getOutline(view: View, outline: Outline) {
            view.run {
//                val borderWidth = (height * borderWidthPercent)
                val outlineSize = (height * CIRCLE_PERCENT).toInt()
                val left = (width - outlineSize) / 2
                val top = (height - outlineSize) / 2

                outline.setOval(
                    left, top,
                    left + outlineSize, top + outlineSize
                )
            }
        }
    }

    init {
        outlineProvider = circleOutlineProvider
        clipToOutline = true
    }

    override fun getOutlineProvider(): ViewOutlineProvider {
        debug("getOutlineProvider !")
        return circleOutlineProvider
    }

    companion object {
        const val BORDER_PERCENT = 0.07f
        const val CIRCLE_PERCENT = 1f - BORDER_PERCENT
    }
}
```
