### ISSUE TITLE
Preview skewed  when rotating phone while previewing/streaming

### ISSUE THREAD

**Issue by Sermilion** [pedroSG94/rtmp-rtsp-stream-client-java#291]
Hi. Almost everything works great. Thanks for this library, appreciate your work. 
I am not really good with using camera or SurfaceView. I followed your basic example and streaming is fine. I only use portrait orientation in my app. My preview (SurfaceView) is squared, not fullscreen. It shows preview stretched and when I rotate my phone it gets skewed while rotating and when rotation to landscape is finished it is, obviously stretched even more. I know this is not a problem of this library, but I was hoping you would help me to display it correctly. 

Using `camera.prepareVideo(width, height, fps, videoBitrate, isHardwareRotatation, rotation)` does not change anything. I tried different width and height values to test but it does not make any difference. Thank you.

**Comment by pedroSG94** [comment]
If you want set the real resolution to preview I recommend you use OpenglView or LightOpenglView instead of surfaceview (API 18+) and set keepAspectRatio to true:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/res/layout/activity_open_gl.xml#L12

If you need support API 16 and 17 you can use TextureView and set aspect ratio manually like in texture example (In this example require API21 because this is using camera 2 but you can replace RtmpCamera2 to RtmpCamera1 and work in API 16 and 17):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/texturemodeexample/TextureModeRtmpActivity.java#L186
