### ISSUE TITLE
How to play send mpa4-simple or aac-lc audio stream as HTML5 does not support mpa4-latm?

### ISSUE THREAD

**Issue by nirukk52** [pedroSG94/rtmp-rtsp-stream-client-java#292]

**Comment by pedroSG94** [comment]
mp4a-latm and aac is the same. 
This library is developed to work with aac-lc because all android device support this format but you can change it with mininal lines of code in audio paquetizer and audio encoder.
You can do only audio stream with this class:
[RtmpOnlyAudio.java](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpOnlyAudio.java)
[RtspOnlyAudio.java](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtsp/RtspOnlyAudio.java)
Code example:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/285

You need a media server and send stream to it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Media-servers-tested

You can test that all is working with VLC or ffplay.
Then you can take a RTMP or RTSP player and get stream in web to replace VLC desktop app.

**Comment by nirukk52** [comment]
Can I do video only?

I want to stream video only or video audio in HTML5.

**Comment by pedroSG94** [comment]
Yes you can use camera1 or camera2 and mute audio. Basic example:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/app/src/main/java/com/pedro/rtpstreamer/defaultexample

You can mute audio with this method:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L479
