### ISSUE TITLE
RTMP stream with socket

### ISSUE THREAD

**Issue by vijai1996** [pedroSG94/rtmp-rtsp-stream-client-java#300]
Hi,
Is it possible to stream to RTMP server using socket or parcelFileDescriptor? I have a screen recorder using mediarecorder and would wish to reuse the code and somehow use the ParcelFileDescriptor to stream to the server? Looking for something like which would connect to the rtmp server and then set the stream from where it reads the stream and writes to rtmp server.

**Comment by pedroSG94** [comment]
If you can get ByteBuffers in H264 and AAC you can use rtmp module and send video and audio. You can see how to use this module here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera1.java

You can do a little modification to the library and replace Mediacodec.BufferInfo with a timestamp because only timestamp is needed in this object.
