### ISSUE TITLE
Incorrect frame rate sending 

### ISSUE THREAD

**Issue by waqarjamsheed** [pedroSG94/rtmp-rtsp-stream-client-java#327]
I am streaming using rtmp. I setup 30fps on app but its sending incorrect fps.

Can you help me why its behaving like that?

![IMG](https://user-images.githubusercontent.com/7131090/56420911-70a76080-62b9-11e9-9b16-51b17bd5d681.png)

**Comment by pedroSG94** [comment]
I disabled fpslimiter because this produce audio sync problems in stream. For this reason this number is not relevant if you are using a mode that render with surface. Anyway I will check this because that fps is not real because your display can't render more than 60fps. So it is imposible in display mode.
