### ISSUE TITLE
Record is failing after few hours of continuous running

### ISSUE THREAD

**Issue by Shanmugamsundarrajan** [pedroSG94/rtmp-rtsp-stream-client-java#354]
In my application, steps followed are
1. Keep recording for about 2 minutes. 
2. Take an current image from the recording for every 2 secs
3. In between if streaming is called due to any alarm, I am stopping the recording. again start the recording and then start streaming. As I wanted to store only the recording which I am streaming to the server

4. The above is working fine

Only issue, randomly after few hours or so, the recording fails saying "java.lang.IllegalStateException: Can't stop due to wrong state". 

This i analysed and found that during recording itself the system has gone to some illegal state, so while the time has reached to stop the record and while calling the stop record, the above exception is thrown.
After which the recording video size is 0 always. We cannot recover from that state. The only way to recover is to restart the system.

Can you suggest on how to address this issue

**Comment by Shanmugamsundarrajan** [comment]
Also I have observed few times while streaming I am getting the below message continuously

RtspSender: Video frame discarded
RtspSender: Audio frame discarded 

what may be the significance of this ?

**Comment by pedroSG94** [comment]
Hello, sorry for late response.
I will try found the error.
This is not related with video record. Only is a log info that show you when device generate frames more fast than send to server (Normally, connectivity reason).

**Comment by pedroSG94** [comment]
Hello, can you tell me version used?
Theoretically you can't get this error in last version because this error is catched.
This should be throw when you stop record before receive a key frame that could be possible if you stop record so fast or your encoder never create a keyframe (encoders normally start with a keyframe so this is so rare).
For this reason I added a listener in startRecord:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L252

If you stop when callback status is RECORDING. You never should get this error. If you stop it in STARTED state you will create a file with 0 size but never a error (Stop error catched):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/RecordController.java#L50

**Comment by Shanmugamsundarrajan** [comment]
Thank you for your response, I will check through this and will reply back
