### ISSUE TITLE
Wrong orientation using Camera2 and Wowza

### ISSUE THREAD

**Issue by 3akat** [pedroSG94/rtmp-rtsp-stream-client-java#370]
Hi!
First of all thanks for the great library!

The issue: video rotated left, see screenshot  
![image](https://user-images.githubusercontent.com/2178533/60953358-b185a300-a305-11e9-80cc-a3ad7ec12f16.png)  

Steps to reproduce:  
 - download current (10.06.2019) version of the library
 - create Wowza RTMP stream without auth
 - use Wowza streaming URL in `TextureModeRtmpActivity` or replace `Camera1` with `Camera2` in `RtmpActivity` and use the link there

**Comment by pedroSG94** [comment]
Did you selected video rotation in prepareVideo with this method?
```java
CameraHelper.getCameraOrientation(this);
```
If yes, the reason is that your video encoder doesn't support rotation:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L116
Mediacodec ignore this params if your encoder doesn't support it.
For this reason I recommend you replace your textureview to lightopenglview and set app:keepAspectRatio=true in xml. 
With lightopenglview you are doing rotation with GPU.

**Comment by 3akat** [comment]
Thanks for the super fast reply!
Yup, it is using `CameraHelper.getCameraOrientation(this);` inside.
A few questions then:
 - Is encoder different in different devices? 
 - Can I somehow get info which encoder is used?
 - Camera1 works fine, is this because of additional forced rotation in `VideoEncoder`?
```  
buffer = isYV12 ? YUVUtil.rotateYV12(buffer, width, height, orientation)
                           : YUVUtil.rotateNV21(buffer, width, height, orientation);
```

**Comment by pedroSG94** [comment]
Use this method to show all encoders in your device: 
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/utils/CodecUtil.java#L28

The encoder used is the first in the list that support H264/AAC. Except with audio that try use an encoder different to omx.google if not found then select omx.google

Also with that class you can filter encoder by type supported.
I don't know a way to know if an encoder support rotation to notify user this error.

**Comment by 3akat** [comment]
Roger! Thanks a lot for the info, will try with GL preview.
