### ISSUE TITLE
Local recording with service and different quality

### ISSUE THREAD

**Issue by maxcriser** [pedroSG94/rtmp-rtsp-stream-client-java#394]
Hi,
I use service streaming from your example, but want to record local video with different quality (better than streaming). How i can implement this feature?

**Comment by pedroSG94** [comment]
Hello,
I'm not sure if this is possible. You can't do it with camera1 (because you can render 2 surfaces) but I'm not sure with camera2. I dont know if you can render 2 surfaces with different resolution with camera2 api or this will crash.
But if this is possible you need 2 video encoders (one for stream and other for record).

**Comment by GGPENG** [comment]
Is it possible to record using service? 
Can you help to do that?

**Comment by pedroSG94** [comment]
Record is the same code in all modes:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/defaultexample/ExampleRtmpActivity.java#L157
