### ISSUE TITLE
How to stream 16:9 Video in portrait mode?

### ISSUE THREAD

**Issue by AlexUrrutia** [pedroSG94/rtmp-rtsp-stream-client-java#407]
Hello Pedro!
I want to stream **16:9 video** **in portrait mode only**, my app won't use landscape.
I have this but the preview seems to be stretched, what can I do to stream 1280x720 in portrait 
```
if (rtmpCamera1!!.prepareAudio() && rtmpCamera1!!.prepareVideo(1280,720,30,2000000,false,15,90)) {
            rtmpCamera1!!.startStream(liveStreamingUrl+streamName)

        } else {
            Toast.makeText(this, "encoder not init", Toast.LENGTH_LONG).show()
        }
```

![error222](https://user-images.githubusercontent.com/7042361/63812781-11a1ca00-c8f1-11e9-9079-510b4c3a71f7.png)

**_Gracias!_**

**Comment by pedroSG94** [comment]
Are you using inmersive mode?

**Comment by AlexUrrutia** [comment]
@pedroSG94 any idea on how to achieve this?

**Comment by pedroSG94** [comment]
I can't reproduce it.
Can you tell me your device model?
Do you have this problem only in preview or also in stream / record result?

**Comment by AlexUrrutia** [comment]
Stream goes 720x1280 portrait 
I want to stream 1280x720 on portrait mode but the preview is automatically changed to 720x1280 
Not sure what to change on the code to make it happen

**Comment by AlexUrrutia** [comment]
I’m testing on 5 devices: moto g4 moto e5 Samsung j2 lg volt 

I’m not using full screen 
I’m using surface view , is it better to use open gl?

**Comment by pedroSG94** [comment]
Ah ok. I understand now.
First of all if you want fix preview stretched you should use openglview or lightopenglview with this parameters set to true:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/res/layout/activity_open_gl.xml#L12
About resolution 720x1280 in portrait this is intentional. The idea is emulate a camera app.
If you record a video in a camera app in portrait with resolution to 1280x720 you will get a video like 720x1280 (You are creating a video with 1280x720 but with metadata rotation set to 90 but you can't do it on stream so to fix it I did that rotation manually and we can avoid a bad orientation result).
This a video created with camera app in portrait mode and rotation set to 0 with this ffmpeg command:
```
ffmpeg -i original.mp4 -c copy -metadata:s:v:0 rotate=0 result.mp4
```
[videostest.zip](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/3563528/videostest.zip)

**Comment by AlexUrrutia** [comment]
Ok, I'll try it with a live stream and see if that fixes it, thank you!

**Comment by AlexUrrutia** [comment]
ok I see the videos you posted for download, but the 16:9 video is sideways, so is not usable, I have seen other libraries that can stream video like this one from Larix, so I wonder if this is possible to do here on yours: 
[larixsample_video.zip](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/3564044/larixsample.zip)
![larix](https://user-images.githubusercontent.com/7042361/64083879-f668fd00-ccea-11e9-987f-ece4b8fa8875.png)
![larix2](https://user-images.githubusercontent.com/7042361/64083907-1f898d80-cceb-11e9-8988-7205f19b0705.png)

**Comment by AlexUrrutia** [comment]
I guess this should be a feature request then, to allow horizontal video streaming while in portrait mode, what do you think?

**Comment by pedroSG94** [comment]
In this case you can't get a full screen preview in portrait. You will get a preview with resolution 1280x720 adapted to portrait like in your screenshoot. The result will be the same like in your screenshoot.
I will mark it like feature.

**Comment by AlexUrrutia** [comment]
Pedro, how about if you allow the resolution 720x1280 and then use rotation 90? that way it won't be stretched...
