### ISSUE TITLE
Stream over Usb cam (UVCCamera) not working , only work for Device camera

### ISSUE THREAD

**Issue by mehtahardikr** [pedroSG94/rtmp-rtsp-stream-client-java#488]
Hello @pedroSG94 , @OleksandrAndro :  i have tried surfaceview , textureview and srsFlvMuxer , but not able to stream usb camera over rtmp server.
this library only works for front and back camera of device.
Can you please guide how can i achieve with USB camera live stream ?

**Comment by pedroSG94** [comment]
Unfortunately I can't help you more than in the other issue because I don't know how to explain it better. I post you my explanation and let me know where you have problems with you code to fix errors:

You have 2 ways to put data to an VideoEncoder.

- Buffer to buffer:
    This means that you set a byte[] to encoder and get ByteBuffer like result, in H264 in this case.

- Surface to Buffer:
    You will render a surface created by VideoEncoder and get a ByteBuffer like result, in H264 in this case.

The first case you need set a video Frame in YV12 or NV21 format (this is a YUV type) with videoEncoder.inputYUVData() in my case this frame is generated in camera1apimanager here

The second case you need render a surface generated by VideoEncoder. This surface can be renderer with any API like camera1, camera2, openGL, etc. In your case, UVCCamera can render a surface, so this could be useful for you. If you render this surface, VideoEncoder class will detect each time you render a new frame and it will encode it returning a H264 ByteBuffer. If your API only support render a surface at same time but you want a preview. You should use OpenGlView, this class create a surface and link it to render previews surface and VideoEncoders surface doing the work for you.

**I think the best idea is read Camera2ApiManager and replace this class with UVCCamera API in my Camera2Base because Camera2ApiManager always use surface to buffer render.**

**Comment by mehtahardikr** [comment]
But can you help me to replace UVCCamera api with Camera2Base.  As you think this is the best way.

**Comment by pedroSG94** [comment]
I uploaded an old project for it. I'm not sure if it is working, but you can try with it:
https://github.com/pedroSG94/Stream-USB-test

**Comment by mehtahardikr** [comment]
Thanks a lot @pedroSG94  will check and let you know. Thanks again.

**Comment by mehtahardikr** [comment]
@pedroSG94  : Cheers !! Thanks for it. 
i have made couple of changes  to your given code and its working fine for me.

 add permission to manifest file 
  <uses-feature android:name="android.hardware.usb.host" android:required="true" />
and inside  USBBase class
inside `startEncoders(UVCCamera uvcCamera)`  method 
just comment  `uvcCamera.stopPreview();`  this line.

i am posting here because it might helpful to others.
