### ISSUE TITLE
autoFocus failed

### ISSUE THREAD

**Issue by K0EZ** [pedroSG94/rtmp-rtsp-stream-client-java#49]
Hello,

on some cheap devices that not supporting autofocus on front cam i always gets this error
"autoFocus failed"

note : we changed the default starting camera to front cam instead of rear cam.

**Comment by pedroSG94** [comment]
I assume that the problem is with camera1api.
I never see this bug with my devices. I need know device that get this problems and try get to debug.
Anyway you can see this post and try fix:
https://stackoverflow.com/questions/8820702/autofocus-throwing-exception
If you fix the problem post the code fix to implement :)

**Comment by K0EZ** [comment]
adding try catch exception fixed it ,but auto-focus may not work on some old and rare devices which is not problem at all

`try{ 

if (supportedFocusModes != null && !supportedFocusModes.isEmpty()) { if (supportedFocusModes.contains(Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE)) { parameters.setFocusMode(Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE); } else if (supportedFocusModes.contains(Camera.Parameters.FOCUS_MODE_AUTO)) { parameters.setFocusMode(Camera.Parameters.FOCUS_MODE_AUTO); camera.autoFocus(null); } else { parameters.setFocusMode(supportedFocusModes.get(0)); } }

} catch (Exception e) { }`
