### ISSUE TITLE
Record delay

### ISSUE THREAD

**Issue by viethoangtien** [pedroSG94/rtmp-rtsp-stream-client-java#504]
Hi,
I am developing my app for lecturer but when i record screen in device, video will delay about 
4-10s. How to fix it?
Thanks.

**Comment by pedroSG94** [comment]
Delay has multiple reasons. Your connection, my library, server and player.

About my library this is bassically related with your device speed doing frame render (GPU), encoding and packetization (CPU). I haven't a big buffer queue that could produce delay. 

My queue is only 80 packets (Audio and Video) that is less than 0,5s. This queue is because the connection could be bad and I discard packets in this queue if you can't send packet faster than device produce it to avoid memory problems.

Also in your case (DisplayMode) MediaProjection API has delay. 
So I recommend you try with Camera example to know how much delay could produce MediaProjection API. If you get similar delay try with other server and player in local net.

I have about 1s in local net with rtsp and rtmp using this server and VLC player with camera examples:
https://github.com/iizukanao/node-rtsp-rtmp-server

**Comment by openmotion** [comment]
i reduced the buffering using ffplay 
ffplay -fflags nobuffer rtmp://xxx:1935/liveest -loglevel verbose
