### ISSUE TITLE
WOWZA Cloud not working

### ISSUE THREAD

**Issue by Geremp** [pedroSG94/rtmp-rtsp-stream-client-java#513]
Hello,

I try your application with my Android phone : Honor 20 Lite.
I test with "Default RTMP" example.
I put my url to connect to wowza cloud, your app says that i am connected.

I try to see the result into Wowza Player, I can see that i am stremaing ("live" word is showing on th e player) but i have no image…

Do you have any solution ?

**Comment by Geremp** [comment]
Just to specify, i have an ULL target : Ultra Low Latency Target.

**Comment by pedroSG94** [comment]
Check in device logcat that you can see video and audio packets. If you can see that, we can discard wowza player problems using VLC or ffplay.
Finally, try change low latency to normal latency to detect the problem.

**Comment by Geremp** [comment]
Thank for your fast answer :).

So yes i can see packets : 
 2020-03-17 18:15:04.573 22393-22625/com.pedro.rtpstreamer D/RtmpConnection: wrote packet: RTMP Video, size: 4286
2020-03-17 18:15:04.593 22393-22625/com.pedro.rtpstreamer D/RtmpConnection: wrote packet: RTMP Video, size: 5183

Just to let you know, with Ultra Low Latency, we have 2 urls to see the stream on a player : 
- wss://edge.cdn.wowza.com/.../stream.ws
And a nother one : 
- https://wowzaprod143-i.akamaihd.net/hls/live/../playlist.m3u8

With the first one : WSS:// is not working (it is the ultralow latency url)
With the 2nd : https:// .M3u8 : it is working, but it is not Ultra low latency.
Maybe the process of the stream is not working properly for ultralow latency ?

**Comment by pedroSG94** [comment]
I don't know reason but a pusher hasnt any difference in normal or low latency (normally is server because he is doing resolution resize to get multiple resolutions and / or change protocol).
Did you try with RTSP?
.M3u8 is hls player so latency is the chuck size. 
Did you try a RTMP player like VLC? 
Also you can get a flash player rtmp to test it in web. You have multiple options in internet.

Unfortunatelly I can't help you to solve your wss player without logs error (If you have, we can try solve it) but normally latency is server and player responsability because my pusher delay is basically (render delay + encoding delay + packetization delay + connection delay).
The only way to reduce it is library optimization

**Comment by Geremp** [comment]
I will have a test with WOWZA team to see the log with your app.
I will tell you then what is happening !

**Comment by Geremp** [comment]
Here the message of Wowza Team : 
I see the issue with the WOWZ option: 

ERROR: PlayerStreamer: unknown videoCodec
wowzaplayer.js:11 00:00:24.957 ERROR: PlayerStreamer: unknown audioCodec
wowzaplayer.js:11 00:00:24.957 INFO: PlayerStreamer: creating sourceBuffers: videoCodec: audioCodec:
wowzaplayer.js:11 00:00:24.957 WARN: AssetPlayerBase: Error occurred: Unable to play: no audio or video codec specified

The player attempts to decode the stream and no codec details are available.  When we transmux the stream for HLS, we are setting the default h264 and aac details and it works. 

What options do you have within your encoder to set this information?

**Comment by pedroSG94** [comment]
I set codec info in connect command:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L190
Page 30:
https://wwwimages2.adobe.com/content/dam/acom/en/devnet/rtmp/pdf/rtmp_specification_1.0.pdf

**Comment by Geremp** [comment]
Thank you for the détail. 
Here the answer of wowza team : 
Hello Jeremie,

I see in your sample code the below values for video and audio:
      args.setProperty("audioCodecs", 3575);
      args.setProperty("videoCodecs", 252);

Unfortunately, I did not see anywhere in the GitHub repro, what profiles these equal.

I do see the below:
Force H264 and AAC Codec hardware/software encoding (Not recommended).

on the home page:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java

I would recommend reviewing if this can be forced.

Have you tried another Android device to see if you have better results? What current device are you testing with?

-> so how can I force h264 and AAC ?

**Comment by pedroSG94** [comment]
Force software and hardware codec is not for that. 
This is because you have multiple codecs in device to do encoding and this line force to use a software or hardware codec but this isn't effect in rtmp protocol.
That line only effect to this classes:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/audio/AudioEncoder.java

We can try set videocodec and audiocodec values of official documentation to test it:
- AudioCodec: Page 31 - SUPPORT_SND_AAC -> 0x0400
- VideoCodec: Page 32 - SUPPORT_VID_H264 -> 0x0080
https://wwwimages2.adobe.com/content/dam/acom/en/devnet/rtmp/pdf/rtmp_specification_1.0.pdf

You need change it in three places:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L190
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L226
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L264

About, why 252 and 3575 values? The reason is because this library is an adaptation of other library and that library use that values. It was working until now so I didn't any change to it:
https://github.com/faucamp/SimpleRtmp/blob/master/src/com/github/faucamp/simplertmp/io/RtmpConnection.java#L255

**Comment by pedroSG94** [comment]
I did a commit to delete duplicate code. Now, you only need change codecs here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L206

**Comment by Geremp** [comment]
First thank for your time.
I test to change what you are saying, and it is not working : 

` AmfObject args = new AmfObject();
      args.setProperty("app", appName);
      args.setProperty("flashVer", "FMLE/3.0 (compatible; Lavf57.56.101)");
      args.setProperty("swfUrl", swfUrl);
      args.setProperty("tcUrl", tcUrl);
      args.setProperty("fpad", false);
      args.setProperty("capabilities", 239);
      //args.setProperty("audioCodecs", 3575);
      //args.setProperty("videoCodecs", 252);
      args.setProperty("audioCodecs", 0x0400);
      args.setProperty("videoCodecs", 0x0080);
      args.setProperty("videoFunction", 1);
      args.setProperty("pageUrl", pageUrl);
      args.setProperty("objectEncoding", 0);`

Do you have any idea ?
Maybe i set property badly …

**Comment by pedroSG94** [comment]
Seems good.
Maybe we can try replace hexadecimal number with the number in decimal:
0x0400 -> 1024
0x0080 -> 128
Also try use this values (librtmp is used in ffmpeg so this should be correct values):
https://github.com/ossrs/librtmp/blob/feature/srs/librtmp/rtmp.c#L347

If this isn't working, Maybe they means this command:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L311
This is the documentation about this command (Page 78):
https://www.adobe.com/content/dam/acom/en/devnet/flv/video_file_format_spec_v10_1.pdf
Try modify it with your stream details. If this isn't working. Can you ask wowza team how we should send codec details properly?

**Comment by Geremp** [comment]
Ok so I try : 
`args.setProperty("audioCodecs", 1024); 
args.setProperty("videoCodecs", 128); `
-> Not Working

`args.setProperty("audioCodecs", 3191); 
args.setProperty("videoCodecs", 252; `
-> Not Working

`private void onMetaData() {
    if (!connected || currentStreamId == 0) {
      Log.e(TAG, "onMetaData failed");
      return;
    }

    Log.d(TAG, "onMetaData(): Sending empty onMetaData...");
    Data metadata = new Data("@setDataFrame");
    metadata.getHeader().setMessageStreamId(currentStreamId);
    metadata.addData("onMetaData");
    AmfMap ecmaArray = new AmfMap();
    ecmaArray.setProperty("duration", 0);
    ecmaArray.setProperty("width", videoWidth);
    ecmaArray.setProperty("height", videoHeight);
    ecmaArray.setProperty("videodatarate", 0);
    ecmaArray.setProperty("framerate", 0);
    ecmaArray.setProperty("audiodatarate", 0);
    // @see FLV video_file_format_spec_v10_1.pdf
    // According to E.4.2.1 AUDIODATA
    // "If the SoundFormat indicates AAC, the SoundType should be 1 (stereo) and the SoundRate should be 3 (44 kHz).
    // However, this does not mean that AAC audio in FLV is always stereo, 44 kHz data. Instead, the Flash Player ignores
    // these values and extracts the channel and sample rate data is encoded in the AAC bit stream."
    ecmaArray.setProperty("audiosamplerate", 44100);
    ecmaArray.setProperty("audiosamplesize", 16);
    ecmaArray.setProperty("stereo", true);
    ecmaArray.setProperty("filesize", 0);
    ecmaArray.setProperty("SoundFormat", 15);
    ecmaArray.setProperty("FrameType", 2);
    metadata.addData(ecmaArray);
    sendRtmpPacket(metadata);
  }`
-> Not Working

I am asking Wowza to see what meta data they need

**Comment by Geremp** [comment]
Hello, here the answer. Wowza try to help me but not so easy for their, because they don't know your lib :

-------
Hello Jeremie,

When connecting with Android GoCoder SDK and analyzing with ffprobe, I noticed that the below metadata is passed:
  Metadata:
    frameWidth      : 480
    frameHeight    : 640
    displayWidth    : 480
    displayHeight  : 640
    audiochannels  : 2
    aacaot          : 2
    androidRelease  : 10
    androidSDK      : 29
    deviceProductName: Crystal_00WW
    deviceManufacturer: HMD Global
    deviceModel    : Nokia 7.1
  Duration: N/A, start: 0.000000, bitrate: 1562 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(tv, smpte170m/bt470bg/smpte170m, progressive), 480x640, 1499 kb/s, 30 fps, 30 tbr, 1k tbn
    Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp, 63 kb/s

With using VLC, to view the Codec Details, the below is passed on:

​​
<img width="474" alt="Screen Shot 2020-03-25 at 8 39 17 AM" src="https://user-images.githubusercontent.com/6321146/77630914-1d6b7280-6f4c-11ea-9a3d-e4829c763870.png">


Hopefully this will help in your research with your custom app.

I would also suggest testing ULL streaming with our Android GoCoder SDK app to see how it performs for you and to compare the differences between your app:
https://www.wowza.com/pricing/installer#gocodersdk-downloads

--------

I haven't the skill to debug this :(

**Comment by pedroSG94** [comment]
I think, they don't understand the question. I need know how they send metadata using RTMP protocol in GoCoder, not the metadata values. They don't need know my library for it.

Maybe I can investigate it if you let me an endpoint to push and a way to reproduce stream in low latency (an url to put in VLC player for example)

**Comment by Geremp** [comment]
You are right.
I create an ULL stream for you : 
Primary URL 
rtmp://origin.cdn.wowza.com:1935/live/0I0p2TXp2QTJeEx4iYQUPuBYTwsm5912

Playback URLs
wss://edge.cdn.wowza.com/live/_definst_/0P0p2TXp2QTJ3b3ZuVlJhQmhNT3h5822/stream.ws 
https://wowzaprod197-i.akamaihd.net/hls/live/784600/0P0p2TXp2QTJ3b3ZuVlJhQmhNT3h5822/playlist.m3u8 
wowz://edge.cdn.wowza.com/live/_definst_/0P0p2TXp2QTJ3b3ZuVlJhQmhNT3h5822

Let me know the prob / solution :)

**Comment by pedroSG94** [comment]
I was doing test and now I know why they don't understand the question. They are using her own protocol in GoCoder ([wowz](https://www.wowza.com/docs/wowza-gocoder-sdk-faq#what-protocol-does-the-gocoder-sdk-use-to-broadcast-to-wowza-streaming-engine-and-wowza-streaming-cloud-)), not RTMP so the stage is totally different.
I tried stream with ffmpeg (this is a really stable library used in professionals stream apps like [OBS](https://obsproject.com/)) to know if I'm doing something bad but I have same problems that with my library.
I think the reason could be this:
- They only support ultra low latency stream with wowz protocol (maybe this is to force yourself to use GoCoder).
- They can use RTMP for ultra low latency but how ffmpeg is not working they have a special way to set metadata and they don't want share how to do it. I tried modify onMetaData command and I added videocodecid and audiocodecid as I shared you in the [pdf document page 78 E.5](https://www.adobe.com/content/dam/acom/en/devnet/flv/video_file_format_spec_v10_1.pdf). Also I'm sure that this command is working because I tested with [my local server](https://github.com/iizukanao/node-rtsp-rtmp-server) and I added a log [here](https://github.com/iizukanao/node-rtsp-rtmp-server/blob/master/rtmp.coffee#L1428) to know if I send it properly (You can change it to logger.error and you can see it in console. Also you can add a logger.error of requestData.objects[2] that is array of metadata send by my library).

I think they haven't support in ultra low latency for RTMP because they need transform RTMP to wowz protocol and this produce delay.
Of course I tried with OBS but no results only HLS url is working in wowza player. Tutorial used for OBS:
https://www.wowza.com/blog/rtmp-video-wowza-streaming-cloud-ultra-low-latency
Wowza player used in tests:
https://player.wowza.com/builder

**Comment by Geremp** [comment]
Last email : 

------------
Hello Jeremie,

Regarding:
* They only support ultra low latency stream with wowz protocol (maybe
this is to force yourself to use GoCoder).

For ULL ingest we do take in RTMP/RTSP streams and then stream them over WOWZ protocol. WOWZ does not need part of the encoder streaming as the ULL Origin server takes over with converting to WOWZ.

Example ffmpeg command that does work for me:
ffmpeg -f lavfi -re -i testsrc=size=1280x720:rate=25 -f lavfi -re -i sine=frequency=1000:sample_rate=48000 -pix_fmt yuv420p -c:v libx264 -b:v 1000k -g 50 -profile:v main -preset veryfast -c:a aac -b:a 64k -f flv rtmp://origin.cdn.wowza.com:1935/live/0I0p2WUtwTVKijmHHdTugrMQ37ly595b

Playback URL for Wowza Player:
wss://edge.cdn.wowza.com/live/_definst_/0P0p2WUtwTVBFWTU0UGRuSGZIcjN582b/stream.ws

​​![Screen Shot 2020-03-26 at 1 39 22 PM](https://user-images.githubusercontent.com/6321146/77702372-a6b88e80-6fb8-11ea-8844-039c71b450d6.png)

OBS worked well for me as well.

Please feel free to test the above ffmpeg command as it's just a test pattern that comes with ffmpeg.

Since you're having issues with three encoders (custom RTMP, ffmpeg, OBS), I would suggest creating a new ULL Stream Target and see how that performs.

Please also make sure that you publish to origin.cdn.wowza.com

 and playback from edge.cdn.wowza.com (handles playback connections).

**Comment by pedroSG94** [comment]
I don't know. This isn't working for me.
![Captura de pantalla de 2020-03-26 23-31-37](https://user-images.githubusercontent.com/17556876/77703010-0e230e00-6fba-11ea-9319-eba7907400c6.png)

Command:
ffmpeg -f lavfi -re -i testsrc=size=1280x720:rate=25 -f lavfi -re -i sine=frequency=1000:sample_rate=48000 -pix_fmt yuv420p -c:v libx264 -b:v 1000k -g 50 -profile:v main -preset veryfast -c:a aac -b:a 64k -f flv  rtmp://**origin.cdn.wowza.com**:1935/live/0I0p2TXp2QTJeEx4iYQUPuBYTwsm5912

Try create a new ULL to test as they say. We need find a way to do it work with ffmpeg and OBS. If we find a way I can debug based in that encoders

**Comment by pedroSG94** [comment]
I tested in windows 10 with OBS to discard problems with Ubuntu:
![image](https://user-images.githubusercontent.com/17556876/77704667-e5047c80-6fbd-11ea-8552-6c06814cbc7b.png)

**Comment by Geremp** [comment]
Hello Pedro,

I test myself my stream target and it is working with OBS on mac :
![Capture d’écran 2020-03-27 à 00 14 58](https://user-images.githubusercontent.com/6321146/77705487-1716de00-6fc0-11ea-9fef-2a1992449483.png)

I figure out something on wowza player : if in the input "Source Stream (required)" you put at the end of the adress "wss://edge.cdn.wowza.com/live/_definst_/0P0p2TXp2QTJ3b3ZuVlJhQmhNT3h5822/stream.ws" a space like that : "wss://edge.cdn.wowza.com/live/_definst_/0P0p2TXp2QTJ3b3ZuVlJhQmhNT3h5822/stream.ws "

The wowza player show "Live" but the video is not working (black page), but if you remove the end space, it is working.

I guess now you can test and i hope, see what is missing in your lib to work with wowza :)

**Comment by Geremp** [comment]
weird…
Because on the player you don't see "live".
as you can see it is working for me :  

![Capture d’écran 2020-03-27 à 00 40 33](https://user-images.githubusercontent.com/6321146/77706834-bdb0ae00-6fc3-11ea-9569-0d11175c4490.png)

But the delay before the image is showing is about 10secs

**Comment by pedroSG94** [comment]
I haven't any space at the end or at the start in the url in pusher or player.
Do you have a way to test it with windows 10 or Ubuntu? (I haven't a mac).
I can see this if I try open with wowz protocol:
![Captura de pantalla de 2020-03-27 01-29-33](https://user-images.githubusercontent.com/17556876/77709152-6feb7400-6fca-11ea-8779-9f36c45e0668.png)

**Comment by Geremp** [comment]
You are using this payback url : wowz://edge.cdn.wowza.com/live/_definst_/0P0p2TXp2QTJ3b3ZuVlJhQmhNT3h5822
I get the same error.
Use this one : wss://edge.cdn.wowza.com/live/_definst_/0P0p2TXp2QTJ3b3ZuVlJhQmhNT3h5822/stream.ws

And it will work.you will the at the bottom center of the player the "live" text, that means your player receive a stream. 
Wait until 10sec to begin to show an image : 
![Capture d’écran 2020-03-27 à 10 26 25](https://user-images.githubusercontent.com/6321146/77741792-c29e4d80-7015-11ea-8cf3-0fb3ca2ebab9.png)

**Comment by pedroSG94** [comment]
Finally this is working!. I have now the reason:
You shared me this URL:
 wss://edge.cdn.wowza.com/live/**definst**/0P0p2TXp2QTJ3b3ZuVlJhQmhNT3h5822/stream.ws
But the right URL is:
wss://edge.cdn.wowza.com/live/**_definst_**/0P0p2TXp2QTJ3b3ZuVlJhQmhNT3h5822/stream.ws

**Comment by pedroSG94** [comment]
My library is working now
![Captura de pantalla de 2020-03-27 11-49-20](https://user-images.githubusercontent.com/17556876/77749043-a56f7c00-7021-11ea-8fbf-c862981f1541.png)
Update library to this commit:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/596dc8c422819d886b9b9883cd54e34a16081190

**Comment by Geremp** [comment]
Great ! :-). Thank you so much !
