### ISSUE TITLE
Error reason

### ISSUE THREAD

**Issue by mynew-github-account** [pedroSG94/rtmp-rtsp-stream-client-java#515]
Hi 
can you tell me the following error reason and when , why is occurring and how can I prevent it

1.Error configure stream, publish permitted failed

2.Fail to connect, time out

3.Null publish type

4.Error send packet

5.Socket closed

**Comment by pedroSG94** [comment]
1 - Start command is not recived, assume can't start stream and connection is closed.

2 - Typical timeout. Basically you can connect with server for some reason (no internet, server down, etc)

3 - Pusblish string set on publish method is null. If you want stream you should set live always like here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java#L228

4 - Fail to send packet because connection was closed by client or server

5 - Server closed connection suddenly.

**Comment by mynew-github-account** [comment]
One more 
6.Connect error, InputStream closed

And can you also tell how can I prevent it all of the above error, if possible

**Comment by pedroSG94** [comment]
6 - Is the same as 5 but you detect it in different moment. In this case you detect it when you try read from input buffer and this is closed.
To avoid all this cases you only need get a stable internet connection with your server and configure server properly (this last in case 1 because bassically server reject your connection for it).

**Comment by mynew-github-account** [comment]
Hey two more 



java.lang.NullPointerException: Attempt to invoke virtual method 'void java.net.Socket.connect(java.net.SocketAddress, int)' on a null object reference


        
E/RtmpConnection:closeStream failed
E/RtmpConnection: Shutdown socket
    java.net.SocketException: Socket is not connected
        at java.net.Socket.shutdownInput(Socket.java:1567)




What is the condition for these two to occur, because is occur few time only

**Comment by pedroSG94** [comment]
1 - Can you tell me line? If this error is only a logcat you can ignore it. If this is a crash I need know line.
2 - If an I/O error occurs when shutting down this socket (when you stop stream). But this isn't relevant for you this have no effect in the app.

**Comment by mynew-github-account** [comment]
Hi, I couldn't reproduce it again but next time I reproduce will send you a detail log.

One More error 

7.Connection was reset
This is due to internet connection got disconnected right?

**Comment by pedroSG94** [comment]
Yes
