### ISSUE TITLE
Not able to stream video on 60 or 120 FPS....

### ISSUE THREAD

**Issue by ankitda30** [pedroSG94/rtmp-rtsp-stream-client-java#517]
Hi Pedro,
Even when I changed the fps in video Encoder from 30 fps to 60/120 fps and start streaming and I checked frame rate on VLC player then it shows frame rates under 30 fps....
Even my mobile do supports 120 fps slow motion recording.....
Please help me to set fps upto 60/120 fps ....

**Comment by pedroSG94** [comment]
This library use screen render like limit because opengl thread is designed (in my case) to render screen and encoder in the same thread and this produces a 30fps limit.
If you have a device with 60hz screen this should work (not tested).
Anyway, I don't know other way to do it without lose performance (you need create 2 thread of opengl and you will lose performance for sure).
Support 60fps is a good suggestion and I will try develop it, but I can't promise you anything

**Comment by ankitda30** [comment]
Thank a lot Pedro,
I do checked my device it supports 60 fps but changing Fps from 30 to 60 fps streaming and recording out comes under 30 fps only....
I can manage with performance issue for testing...
Could you please guide me what exactly I have to do to change actual fps ....?
**you need create 2 thread of opengl and you will lose performance for sure**
because I'm unable to understand from above line you told.....

Please help.....

**Comment by pedroSG94** [comment]
This is only a general idea so I don't know the exact way to do it. For this reason I marked this issue as enhancement.

I need do multiples test before develop it. For example, I need check if camera2 and camera1 can render a surface with 60fps and how to do it or how to avoid 30fps limited by screen hz (I told you 2 thread of opengl for this last problem but maybe this isn't the right way, the only way to know is testing it).

**Comment by ankitda30** [comment]
Right....
Thanks for the tremendous support.....
