### ISSUE TITLE
Streaming on facebook is slower than mobile. How can I improve this issue, please ? Thank you very much.

### ISSUE THREAD

**Issue by hoangtuanitstar** [pedroSG94/rtmp-rtsp-stream-client-java#521]

**Comment by pedroSG94** [comment]
Can you explain your case with more details?
What do you means with slower than mobile? 

Maybe that you can see in logcat "frame discarded"?
In this case this is related with internet connection, you can try reduce videobitrate and resolution. Also you can use adaptative videobitrate:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Adaptative-video-bitrate.

If the problem is low FPS try with openglview that use opengl instead of manual yuv color conversion and you will get more fps. You can use this method to get a callback with fps sent to server:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L116

**Comment by hoangtuanitstar** [comment]
when I start a stream on mobile and then it will started on my timeline after 7 seconds. It means on my mobile and facebook web to be not showed at the same time

**Comment by pedroSG94** [comment]
Ah ok, you have delay.
7s is a normal delay in platforms like YouTube, Facebook or Twitch because they use HLS protocol in player side.
Delay is basically this:
- Pusher delay (my library) that is the time when you see a frame and frame is ready to send. In my case this is less than 1s in all devices I tested for now.
- Connection delay of pusher with server (this depend of you internet connection).
- Server delay (in this case facebook server) that is doing a rescale resolution and change stream protocol
- Connection delay of player with server (this depend of you internet connection).
- In player side you have a player delay that normally is high because this platforms use HLS and this protocol use chucks of 3-5 seconds of size which produce this delay.

You need sums all this to get your delay.
In my case I tested with local server and RTSP player (ffplay in this case) to reduce delay to max and I can get 0,5s of total delay.

**Comment by abadoliverco** [comment]
hi @pedroSG94 
I have a concern with regards to this

> Maybe that you can see in logcat "frame discarded"?
In this case this is related with internet connection, you can try reduce videobitrate and resolution. Also you can use adaptative videobitrate:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Adaptative-video-bitrate.

I tried to access the link but I can't see the documentation of adaptive-video-bitrate
