### ISSUE TITLE
Unable to reconnect stream after lost internet connection

### ISSUE THREAD

**Issue by Geremp** [pedroSG94/rtmp-rtsp-stream-client-java#526]
Hello Pedro,

I try to handle internet connection loss.
I test it on your app : custom RTMP.

Here the test : 
1 - Launch the stream (button start stream)
2 - You can see that you are streaming and it is ok
3 - Cut the internet connexion (flight mode or wifi connection)
-> you have here to error show with Toast (normal, because we lose the connection):
Error reading packet: Software caused connection abort
Error send packet: Broken pipe 
4 - Reconnect your device to internet
5 - Click again to the button "start stream"
6 - An error occurs : Error configure stream, publish permitted failed

I can't figure out why…

**Comment by pedroSG94** [comment]
I think that reason is that your server have the old connection still up. To check that try change stream name in the second try.

Some servers have a timeout to wait client send packets before delete old inactive connections and delete connection with a new connection is not permitted. This should be configurable (at least in wowza engine and nginx you can do it).

**Comment by Geremp** [comment]
No it is no the reason.
I test with 30sec wait between reconnect, same prob.
I get this message on the debugger : 
I/VideoEncoder: Encoding error
    java.lang.IllegalStateException: buffer is inaccessible
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:287)
        at com.pedro.encoder.BaseEncoder.processInput(BaseEncoder.java:73)
        at com.pedro.encoder.BaseEncoder.inputAvailable(BaseEncoder.java:111)
        at com.pedro.encoder.video.VideoEncoder$2.onInputBufferAvailable(VideoEncoder.java:478)
        at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1738)
        at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.os.HandlerThread.run(HandlerThread.java:67)
D/BufferPoolManager: register existing connection 58962896711781
D/BufferPoolManager: register existing connection 3643717840825

Maybe something wrong with the encoder when the error is thrown

**Comment by Geremp** [comment]
The weird thing is if you : 
- Start stream
- stop stream
-start again (2 second of delay between stop and start) it is working great without problem

**Comment by pedroSG94** [comment]
About VideoEncoder if you only see a logcat don't worry this is working fine. This is a catched logcat controller and only relevant for me if you have a crash and I need debug.

My opinion is still possible with 30s of delay and when you press stop without close connection have all sense because in this last case you send a command to server notifying that you will close connection:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L357
Obviously this isn't possible if you lose connection. For this reason it is my first suspicion

**Comment by Geremp** [comment]
ok I ask Wowza team and get you in touch about this !

**Comment by pedroSG94** [comment]
Before that. Check that you have disabled "Duplicate Stream Names" in the configuration:
![Captura](https://user-images.githubusercontent.com/17556876/78054408-522f5d80-7382-11ea-85ee-1b5677c62c8d.PNG)

Also before press startStream check if you have an stream enabled with the same name:
![Captura2](https://user-images.githubusercontent.com/17556876/78054536-873bb000-7382-11ea-8bc0-4213bfa31e25.PNG)
If all is fine we can discard my suspicion.

**Comment by Geremp** [comment]
I am using Wowza cloud, I have not the same menu than you

**Comment by pedroSG94** [comment]
Can you check If you have that stream active after stop your device connection?
After that wait until stream is inactive to restart stream

**Comment by Geremp** [comment]
I think you are right.
So if this problem occurs, I wait a little to reconnect, and it is working.

Thanks for your time !
