### ISSUE TITLE
Does the RTMP function support H265?

### ISSUE THREAD

**Issue by hawskpy** [pedroSG94/rtmp-rtsp-stream-client-java#534]
We need to push h. 265 video with RTMP, and we need to refer to a Java library。

**Comment by pedroSG94** [comment]
No, This is actually impossible because FLV don't support H265. You can use H265 with RTSP.
Official documentation (Page 18. 1.8.2 - Supported video types):
https://www.adobe.com/content/dam/acom/en/devnet/flv/video_file_format_spec_v10_1.pdf
Also, you can see that in RTMP documentation (Page 33. Flag values for the videoCodecs Property):
https://wwwimages2.adobe.com/content/dam/acom/en/devnet/rtmp/pdf/rtmp_specification_1.0.pdf
You can create your own implementation, but it is unofficial.
