### ISSUE TITLE
Adaptative video(WIDTH and HEIGHT)

### ISSUE THREAD

**Issue by zonell** [pedroSG94/rtmp-rtsp-stream-client-java#543]
Hello
I need to resize the video depending on the internet channel
How to dynamically resize video (like a  bitrate)?
Maybe you have some ready-made solutions for streaming settings.
Maybe best practice

And the second question
_AdapterBitrateParser.maxVideoBitrate_ is deprecated now, what should I use instead?

**Comment by pedroSG94** [comment]
You can't do adaptative resolution because when you connect with server you need inform server about resolution (RTMP and RTSP protocol). 
If you want change resolution you need reconnect with other resolution. That is normally done by the server.
About bitrate adapted (version 1.6.4+):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Adaptative-video-bitrate
