### ISSUE TITLE
Is there a way to get the RtpCamera Session Description without starting to stream?

### ISSUE THREAD

**Issue by gvaness** [pedroSG94/rtmp-rtsp-stream-client-java#553]
First, thanks for the great library, it's helped a lot.

A (hopefully) quick question.

Is there a way to get a RtpCamera1 SessionDescription without calling startStream? Or calculate what the session description will be? Just calling RtpCamera1.getSessionDescription() before startStream throws an exception, seemingly due to sps (and probably pps) being null.

Everything works great if I call it within my override of onConnectionSuccessRtsp()

My use case may be odd, I basically have an app running on multiple devices that I'm streaming video to, but they don't have a reliable means to get the description string to the clients. I can assure that all parties have the same settings though. Each client already sets up a camera based on a common parameter file, so if I could somehow calculate that string it would save a lot of problems.

**Comment by pedroSG94** [comment]
I think you are using a wrapper or an old version of this library because I haven't that method.
![Captura de pantalla de 2020-04-29 20-21-04](https://user-images.githubusercontent.com/17556876/80632070-fa564600-8a56-11ea-8be9-1fd86e9aa9dd.png)
If you want get video info you have this methods:
```java
rtspCamera1.getBitrate();
rtspCamera1.getStreamWidth();
rtspCamera1.getStreamHeight();
```
If you want get other method I recommend you save it in a list and remember that before prepareVideo or prepareAudio. You can't get values because anyone is selected so stream is not confiured (Of course, you can call prepare method and no start stream in that moment)

**Comment by gvaness** [comment]
Thanks.
You're correct, it appears there was a wrapper added. commandsManager.createBody() was what is being called.

It seems the string is easy to construct, I was just relying on the above call to get the constructed sps and pps strings. 

At the moment, I've saved off a few of the common combinations and just use them on the receiving side. This seems to work well, I'll continue down this route for now.

Thanks for the help.
