### ISSUE TITLE
Resize video (OpenGlView) on the fly

### ISSUE THREAD

**Issue by Racker79** [pedroSG94/rtmp-rtsp-stream-client-java#569]
Hello again.

I am trying to implement a function to resize the video based on the resolutions that the camera is capable of supporting.

I have implemented a small function:

public void changeVideoResolution (int width, int height) {
    prepareVideoEncoder (width, height, fps, bitRate, rotation, hardwareRotation,
            iFrameInterval, formatVideoEncoder, -1, -1);
  }

And to apply it I do the following:

rtspServerCam !!. changeVideoResolution (176, 144)
rtspServerCam !!. replaceGlInterface (rtspServerCam !!. glInterface)

Although it works, I have detected that sometimes (I don't know which ones yet), the application goes black and the application crashes.

Is there any other way to make this image resize?

Thanks again!!!

**Comment by pedroSG94** [comment]
First of all. 
Resize video on fly is not possible for stream because RTMP and RTSP need inform to server resolution used in stream before you start it (this is specified in protocol). The reason is because a player need know it to reproduce the video.

This feature should be developed in server side where you have multiple endpoint and player can change endpoint on fly to reproduce other resolution.
For example, you can do it with wowza server. Also, others stream platforms like youtube or twitch can do it.

If you want change resolution in client side you only can stop stream totally and re start with other resolution.

**Comment by mhoyosga** [comment]
Ok, but it does work. The problem is that sometimes the screen is blocked
and I have not been able to determine under what circumstances it occurs.

**Comment by pedroSG94** [comment]
Can you share a logcat of your crash?

**Comment by CubitSpeed** [comment]
@Racker79  -- did you ever make any progress here? I'm interested in the code that you were using.
