### ISSUE TITLE
Floating Widget when app in background

### ISSUE THREAD

**Issue by anupdey99** [pedroSG94/rtmp-rtsp-stream-client-java#587]
Thanks for this awesome library.
Show camera preview in floating widget when app in background will be a nice addition to this library.

Any guide line for this?

**Comment by pedroSG94** [comment]
Hello,
I think that develop a widget is not necessary in a stream library and each developer should do it by herself, because that is a specific case for each one.
You have multiple ways to do it using libraries or by yourself. This post could help you:
https://stackoverflow.com/questions/11443820/floating-widget-overlay-on-android-launcher
