### ISSUE TITLE
Switch between rtmpcamera and rtmpdisplay

### ISSUE THREAD

**Issue by mynew-github-account** [pedroSG94/rtmp-rtsp-stream-client-java#624]
Is there any way so that I can switch between screen capture and camera capture while streaming , without disconnecting ??

**Comment by pedroSG94** [comment]
Actually no. I haven't this feature developed.

**Comment by mynew-github-account** [comment]
Are you going to work on this soon??

**Comment by pedroSG94** [comment]
I have plan to do it but this is a really big change for the library, because after that, keep all modes separated has no sense and I should create a builder that support change mode and view used on fly.
I have plan to do it but no soon

**Comment by mynew-github-account** [comment]
ok cool, but can you tell how much time it will take you to complete?

**Comment by pedroSG94** [comment]
I don't know. 
I can't give you a date because I do it in my free time so maybe I do it fast because I have time or I don't do anything in weeks.

Actually I'm reading about HLS because I want try add this to the library, but this seems really difficult because android doesn't support mpeg2 format before api 26, so maybe I stop it and start with this feature.

**Comment by mynew-github-account** [comment]
Hi 
Any updates on this??

**Comment by pedroSG94** [comment]
No for now.
I will try work on it this week

**Comment by mynew-github-account** [comment]
Hi
Any updates on this??
