### ISSUE TITLE
Error after cancel MediaProjection prompt

### ISSUE THREAD

**Issue by luliou** [pedroSG94/rtmp-rtsp-stream-client-java#638]
The activity will close after click CANCEL in the first time in prompt.

Can we only click once / bypass about the permission? because every time while click start and stop the stream button, we must click the mediaProjection prompt.
![Screenshot_20200801-063233](https://user-images.githubusercontent.com/69023165/89082678-418b0480-d3c1-11ea-8af2-306c7b851908.png)

**Comment by pedroSG94** [comment]
Error fixed: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/87c7d33062197cc37cde7742db7e201461efc8ac

You can't omit the permissions or click only once because this type of permissions was developed by google to keep user privacy to avoid spying on user data without their consent.
For this reason, also you have an icon in notification bar when this feature is recording.
