### ISSUE TITLE
Crash application on stopping translations with RtmpCamera2

### ISSUE THREAD

**Issue by ezhov-evgeny** [pedroSG94/rtmp-rtsp-stream-client-java#641]
**Preconditions:**
- Problem reproduces on examples version 1.8.5.
- Android Emulator with API 24 (the same for 29)
- For receiving RTMP I use docker image `hink/node-rtsp-rtmp-server`
```
docker pull hink/node-rtsp-rtmp-server

docker run -d -p 1935:1935 -p 8020:80 --name node-rtsp-rtmp-server hink/node-rtsp-rtmp-server
```

**Steps to reproduce:**
1. Open Example app
1. Open one of the following activities: "Surface mode RTMP", "Texture mode RTMP", "Display RTMP"
1. Enter valid rtmp url
1. Start translation, after any time stop translation (if needed repeat this step few times)

**Expected result:**
Translations starts and stops correctly

**Actual result:**
Application crashes without any stacktrace and messages in Logcat, crashlyticts doesn't register any crashes.

**Note**
- RtmpCamera1 works well in example app.
- Problem doesn't reproduces on version 1.6.6

**Comment by pedroSG94** [comment]
I can't reproduce it. I'm using AVD (pixel 3 with x86 and API 29) in android studio
Can you specify emulator used? 
Device model, architecture (x86 or ARM), program used (Android studio or other program), etc.

**Comment by ezhov-evgeny** [comment]
I'm using Android Studio 4.0.1, AVD and Custom 720x1440 xhdpi API 24 x86.

Now I created the same Virtual device as yours (Pixel 3 API 29 x86) – it isn't reproducing there.
Then I double checked Custom 720x1440 xhdpi API 29 x86 – it isn't reproducing.

Also I created video with crashes:
https://drive.google.com/file/d/1vRJhiTcg2KMkrn-aCiR1QE8CQ-Bw4fyE/view?usp=sharing

**Comment by pedroSG94** [comment]
I can reproduce this error and it seems to be an internal API error.
In first one, I'm 100% sure that anything is null because I checked all in stopRepeatingEncoder method (that method produce that crash):
![Captura de pantalla de 2020-08-16 23-56-27](https://user-images.githubusercontent.com/17556876/90345593-391e0500-e022-11ea-9bcc-d2761500b4d1.png)
In the second case, I'm using openglview and it seems a crash related with opengl because in this case stopRepeatingEncoder is not called, in fact, cameramanager is not called:
![Captura de pantalla de 2020-08-17 00-32-16](https://user-images.githubusercontent.com/17556876/90345604-463af400-e022-11ea-9967-fd3ae5e3e136.png)


I have same error using 1.6.6 version. I tested it downloading zip from here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tags

I think that this is an API error using hardware graphics because if you change to software graphics all is working fine with same emulator (automatic seems to use hardware graphics):
![Captura de pantalla de 2020-08-17 00-28-19](https://user-images.githubusercontent.com/17556876/90345620-6d91c100-e022-11ea-8db4-3afc64a09cc2.png)
As you can read in android studio description this could be an error in certain GPUs or maybe directly a bug in the ROM so I can't do anything for it.

**Comment by ezhov-evgeny** [comment]
@pedroSG94 thank you!
