### ISSUE TITLE
Stream sometimes unable to connect

### ISSUE THREAD

**Issue by ClaytonLoh** [pedroSG94/rtmp-rtsp-stream-client-java#642]
On my app it states: Retry. Reason: Error send packet: Write error:ssl=0x7653b08d08: I/O error during system call, Broken pipe. I uploaded what is stated on the console. Please help me, thank you

<img width="1150" alt="Capture2" src="https://user-images.githubusercontent.com/47517310/90340009-a718fb00-e027-11ea-8424-e5272ec16c79.PNG">
<img width="1392" alt="Capture" src="https://user-images.githubusercontent.com/47517310/90340010-a8e2be80-e027-11ea-8702-26447f105837.PNG">

**Comment by pedroSG94** [comment]
Your error seems to be that your server close connection for some reason. 
Make sure that you set port correctly. Remember that default port for RTMP and RTMPS is 1935 in this library not 443.
Also check with other app to know if you server is working correctly. For example [OBS](https://obsproject.com/)
After that if your problem persist and OBS is working let me know server used to test.

**Comment by ClaytonLoh** [comment]
I am still facing the issue. I am using Amazon IVS for this project, it is stated that they need to use port 443 for it to work (Link: https://docs.aws.amazon.com/ivs/latest/userguide/GSIVS-live-streaming.html)
I have no issues when using obs

**Comment by pedroSG94** [comment]
You can't connect never or only sometimes?
I have 2 users working with Amazon IVS. Check this issue and try connect like I indicate here: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/630#issuecomment-666394993
Also check that you have all permissions requests (camera, microphone, write/read files if you want record and internet) in your app and you are in the same net that your server. Try doing a ping to server or anything to confirm a response from server using that device.

That transport error is normally because you can't connect with that server (unreachable) and camera error is because you haven't camera permissions. To discard this, try with my default app without modify anything.
