### ISSUE TITLE
I want to play rtsp streaming on my device with no camera , did it support ?

### ISSUE THREAD

**Issue by Tairr** [pedroSG94/rtmp-rtsp-stream-client-java#643]
Look forward to your reply.  Thanks .

**Comment by pedroSG94** [comment]
Maybe I'm wrong, but if you are looking for a rtsp player (like ijkplayer or vlc). This library is a pusher not a player.
You can stream rtsp using only audio or device's screen. Examples:
Only audio (microphone needed):
```java
//create builder
RtspOnlyAudio rtspOnlyAudio = new RtspOnlyAudio(connectCheckerRtsp);
//start stream
if (rtspOnlyAudio.prepareAudio()) {
  rtspOnlyAudio.startStream("rtsp://yourEndPoint");
} else {
 /**This device cant init encoders, this could be for 2 reasons: The encoder selected doesn't support any configuration setted or your device hasnt AAC encoder (in this case you can see log error valid encoder not found)*/
}
//stop stream
rtspOnlyAudio.stopStream();
```
Device screen (microphone needed in this example but if you delete prepareAudio() method, microphone is not necessary. Also you can use prepareInternalAudio() instead of prepareAudio() to use internal device sound):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/app/src/main/java/com/pedro/rtpstreamer/displayexample
