### ISSUE TITLE
Recordings broken sometimes 

### ISSUE THREAD

**Issue by mkrn** [pedroSG94/rtmp-rtsp-stream-client-java#665]
What could be a reason for a broken recording file? 
Sometimes users get a recording that is not playable (missing moov atom) - i.e. not properly finalised.

Sometimes it happens, even if next recordings are successful.

The exact reasons unknown. Want to check to make sure that recordings close properly if the app goes to background, RTMP disconnects, app quits, or storage is full.

**Comment by pedroSG94** [comment]
Hello,

This could be because stopRecord is not called properly or because encoder never generate generate a keyframe resulting in an unplayable file. This last one could be solved in this commit:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/664
Also you can be sure that record started or stopped properly using record listener when you call startRecord method and track status recording and stopped.
