### ISSUE TITLE
Fps 60

### ISSUE THREAD

**Issue by exxKx** [pedroSG94/rtmp-rtsp-stream-client-java#668]
Hi Pedro,
60 fps streaming feature is not expected in the near future? 
We need it very much.)
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/517

**Comment by pedroSG94** [comment]
I want do it, but this feature is only supported by few devices using camera api 1 and 2. Normally google pixel and I haven’t one to test.
It means that if you want record 60fps you need use mediaRecorder api so I can’t extract buffer to encode because this api write a file in disk directly (view set to that api render to 30fps, only video result has 60fps).

If you can find a way to render a surface with 60 FPS share me a code example and I will add it.
You are totally free to modify my code to test.
