### ISSUE TITLE
Weird Screen when broadcasting screen

### ISSUE THREAD

**Issue by MingLoan** [pedroSG94/rtmp-rtsp-stream-client-java#74]
<img width="673" alt="sample" src="https://user-images.githubusercontent.com/5032142/31862481-0d252456-b771-11e7-9f4b-ebe20222d52e.png">

How to fix the above issue?
Any hints for the duplicated screens?

**Comment by MingLoan** [comment]
device: Samsung C7000

**Comment by pedroSG94** [comment]
I never see that.
I think this bug is player side that maybe doesn't work properly because when you use this mode only render and send video packets when your screen refresh. Try with VLC or ffplay to confirm it.
Display mode work like camera2 but MediaRecorder api render the surface instance of camera2 api so if that mode work for you this is so rare.
