### ISSUE TITLE
Video output blur while moving camera

### ISSUE THREAD

**Issue by anirudhwynk** [pedroSG94/rtmp-rtsp-stream-client-java#750]
Hi pedro,

I am getting some issues, while using RTMP publisher with RtmpCamera2.
Output video getting blur while moving camera and if camera move to PC screen, output stream text not readable for 2-3 sec.
I also tried to disableAutoFocus(), but it not work.
Is there any option to get better quality video stream?

**Comment by pedroSG94** [comment]
Sorry for late reponse. I was in holydays.

This seems related with camera configuration and you can modify this class to adapt it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java#L176
You can configure camera as you want after addTarget. You will need study a bit about camera2 api for this. 
I recomend you test all autofocus supported by your camera reading camera2 api:
https://developer.android.com/reference/android/hardware/camera2/package-summary
The best way is modify enableAutofocus and test all modes supported:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java#L369
Also you can try use other fps configuration because sometimes this could produuce problems in somes devices:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java#L188

**Comment by anirudhwynk** [comment]
Thanks for the response pedro
I am getting one more issue in some devices like Oneplus 5t with RtmpCamera2, back camera is too dark or looks low brightness but its working fine with RtmpCamera1 on same device. (I am using OnenGlView with both Rtmpcamera1 and RtmpCamera2)
Also,Some devices working fine with both RtmpCamera1 and RtmpCamera2.
Can you please help me out with this?
