### ISSUE TITLE
Question: display bitrate

### ISSUE THREAD

**Issue by natxopedreira** [pedroSG94/rtmp-rtsp-stream-client-java#786]
Hello

How to tweak stream parameters on display version? i mean for example video bitrate comes from the videoencoder bitrate or for the flvmuxer?

Thank you

**Comment by pedroSG94** [comment]
Video bitrate is always from VideoEncoder.
FlvMuxer only create flv packets using h264 frames (It is add a header).
You can modify video encoder parameters using prepareVideo method.

**Comment by natxopedreira** [comment]
Thank you! and is possible to remove audio?

**Comment by pedroSG94** [comment]
Yes. You can skip call prepareAudio (you will need stop stream and call it if you want enable it) or call disableAudio method if you want do it on fly.
But use last gradle version provided because I did a fix related with that.

**Comment by natxopedreira** [comment]
great!! thank you

**Comment by natxopedreira** [comment]
Hello Again

Skiping prepare audio make the stream to stop, im using last release 1.9.8

```
D/RtmpConnection: wrote packet: RTMP Video, size: 273
D/EGL_emulation: eglMakeCurrent: 0xa0770a20: ver 2 0 (tinfo 0x91aa0630)
D/EGL_emulation: eglMakeCurrent: 0xa0770ba0: ver 2 0 (tinfo 0x91aa0630)
D/RtmpConnection: wrote packet: RTMP Video, size: 48
E/DisplayService: RTP service destroy
E/RtmpConnection: Caught IOException during write loop, shutting down: Broken pipe
```

**Comment by pedroSG94** [comment]
Hello,
Few servers like YouTube or Facebook need both (video and audio) to work so you can't skip configure audio you will need use disableAudio method.
The reason is because:
If you skip configure audio you don't send audio packets needed for few servers but if you mute audio (disable audio method) you are still sending audio packets but only the header producing an effect of mute and working with all severs.

**Comment by natxopedreira** [comment]
ahhhhh.... make sense, thank you
