### ISSUE TITLE
Video freeze few seconds after start

### ISSUE THREAD

**Issue by cyprianG96** [pedroSG94/rtmp-rtsp-stream-client-java#808]
as in title, after start video is freeze.

I use rtspCamera2 and openGL, set properties in .prepareVideo not helped, any ideas?
About 2 weeks ago stream works fine. Everything is based on Wowza.

**Comment by pedroSG94** [comment]
I don't understand.
Do you mean that stream freeze after startRecord?
What do you means 2 week ago all work fine? Did you change library version?
Can you tell me actual version and previous version?

**Comment by cyprianG96** [comment]
Previous version was 1.9.3 now is 1.9.9. So if I start broadcasting everything is fine, in logs I can see all works properly, but if I put my rtsp adress in VLC for example then after 1 sec, screen in player is black.

**Comment by pedroSG94** [comment]
tcp or udp?
Which mode are you using (camera1, camera2)?
Can you hear audio?
Are you using wowza cloud or engine?

**Comment by cyprianG96** [comment]
Camera1, I don't hear anything, engine, TCP

**Comment by pedroSG94** [comment]
Hello,

This is not working in the new version of wowza for some reason and I don't know why. I'm investigating the case. 
Did you updated wowza? 
In case you updated wowza. Library version 1.9.3 still produce this error for me, did you tested it after update wowza?
For now, you can download this version that work:
https://www.wowza.com/downloads/WowzaStreamingEngine-4-7-6/WowzaStreamingEngine-4-7-6-windows-installer.exe
https://www.wowza.com/downloads/WowzaStreamingEngine-4-7-6/WowzaStreamingEngine-4.7.6-linux-x64-installer.run
https://www.wowza.com/downloads/WowzaStreamingEngine-4-7-6/WowzaStreamingEngine-4.7.6-osx-installer.dmg

**Comment by cyprianG96** [comment]
I'm using Wowza 4.8.8 now, but I will downgrade, and let you know if it works, thanks for help :)

**Comment by pedroSG94** [comment]
I don't know which is the last version working but 4.7.6 is working and 4.8.10 is not working using same library version (tested with library versions 1.8.5, 1.9.3 and 1.9.9).

I don't know where is the problem since it is working with others rtsp server solutions.

The weird thing is that if you only stream video or audio all is working fine (we can discard packetizer for this reason) so the only possibility is problems with socket or connection commands. Maybe wowza changed requirements for it but I can find anything about it.

Ffmpeg is working so I tried emulate connections commands but no luck for now

**Comment by pedroSG94** [comment]
I finally fixed it. Last version of wowza is working after this commit:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/db1854eb0b0f370d60039b9b3f5e3e8da12343f9
