### ISSUE TITLE
rotation not working using context

### ISSUE THREAD

**Issue by DaviGia** [pedroSG94/rtmp-rtsp-stream-client-java#81]
Hi, 

I have a device that has only a front camera. I tried to set hardware rotation to true and declared 180 degrees to normalize the capture using the prepareVideo method but the image is not rotating.
I'm using the RtspCamera2 class initialized using context. Is there another way to set the rotation? As I understand while reading online there are some devices that does not care about the rotation you set ("rotation-degrees").

If there is no other way my last chance is to change the MediaCodec input buffer. I think I have to do the same thing you did [here](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L260), but for the camera2 api. Can you help me?

Thanks in advance.

**Comment by pedroSG94** [comment]
If you use camera2 builder you only can rotate using hardware rotation and some devices doesn't support it and ignore it. 
You can't do it because buffer from mediacodec is H264 not YUV and you use surface mode so you haven't input buffer, the buffer is getted from the input surface. The only way (that I know) is with opengl but I'm not sure if you can do it without a preview.

**Comment by DaviGia** [comment]
Ok, so the only way is with OpenGLView. That's very unfortunate. Maybe it's possible declare a metadata tag or something in the SDP structure? I will look for it and let you know. Thanks anyway.
