### ISSUE TITLE
[Question] Filter background removal

### ISSUE THREAD

**Issue by tplloi** [pedroSG94/rtmp-rtsp-stream-client-java#811]
Hi @pedroSG94 , thanks for great lib!
I run your sample and tried to search all issues but I still dont find any filter can remove background/landscape/scene (except people).
The chromakey filter like my case i'm facing, but in this mode only work if the background is green screen.
In case no green screen after people (it can be anything background like the wall, the house, some people, some trees...), how can I implement that?
Thanks in advance.

**Comment by pedroSG94** [comment]
You mean a filter like portrait mode photo used in camera apps right?

This filter is complex to implement and you can't expect a good result because normally all devices use other camera to compare deep and know where do you want to blur (normally an infrared camera).

Of course, you are free to experiment yourself and create your own filter but you need know a bit of opengl:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Real-time-filters

**Comment by tplloi** [comment]
Hi @pedroSG94 , tks for quickly responding.
I meant the filter can remove everything (except people) and make it transparent. Please take a look in these photos below.
The chromakey filter only works if the background behind the singer is green screen, so I can change the background to anything photo I want.
But in case without green screen, how can I detect the singer and the scene behind him. I want to remove the scene by making it transparent. I have no experience with OpenGL but I will try to research it, can you guide me something to make it done?
Please help.
Thank you a ton.

![1](https://user-images.githubusercontent.com/13247132/112756648-5b442080-9010-11eb-97b7-5a0a2f46b167.png)
![2](https://user-images.githubusercontent.com/13247132/112756650-5d0de400-9010-11eb-9de9-67ed6f1a242b.png)

**Comment by pedroSG94** [comment]
Yes, exactly the same thing that I told you. You need 2 cameras to do it. Your effect is the same that this:
https://www.google.com/search?q=portrait+photo&client=ubuntu&hs=2kv&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjo1bvPqNPvAhXEzIUKHTtfAH4Q_AUoAXoECAEQAw&biw=1848&bih=944#imgrc=r6R6hKQmfAEMBM
But instead of blur you want crop and replace image.

For this filter you need open depth camera or sensor and create a map of depth using this map to crop image in the filter. Seems that since android 9 google added an api to open multiple cameras but I think that most of devices don't support it:
https://developer.android.com/training/camera2/multi-camera
If you find a way to create a depth map I can do the filter for you.

**Comment by tplloi** [comment]
Thanks for your information. I will try to research now.
I close this issue and will reopen it later when I found the way can make this filter works.
