### ISSUE TITLE
[Enhancement] Need stopPreview & startPreview function, without checking isStreaming

### ISSUE THREAD

**Issue by KunNiu** [pedroSG94/rtmp-rtsp-stream-client-java#813]
Please think about this case, need to go to another activity to do something, like pick a picture and send out when streaming. In this case, I cannot start preview in surfaceChanged() method, because it will check if onPreview=false, so I need to stopPreview in surfaceDestroyed() method, but stopPreview will check isStreaming, so I need to stopStream, then stopPreview in surfaceDestroyed(), and then I can startPreview and need to startStream again, in surfaceChanged().
This will case frame discarded during the process.

**Comment by pedroSG94** [comment]
I can't do it because you can't skip view lifecycle. For this case you should change render view to background using this:
```java
rtmpCamera1.replaceView(context);
```
When you return to your activity and openglview is ready you should replace view to openglview:
```java
rtmpCamera1.replaceView(openglview);
```
Keep in mind that you need keep rtmpCamera1 alive and avoid call stopStream in this case. Background sample in app is a good example of this use (you can start stream, go back to main activity and stream keep alive until you go to stream activity and press stop button):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/backgroundexample/BackgroundActivity.kt

**Comment by KunNiu** [comment]
@pedroSG94, thanks for your explain, that's very helpful!
