### ISSUE TITLE
Streaming From ImageReader's surface

### ISSUE THREAD

**Issue by tareqalbeesh** [pedroSG94/rtmp-rtsp-stream-client-java#816]
is it possible to stream from an ImageReader's Surface?

**Comment by pedroSG94** [comment]
Yes  because you can use bytes provided by imagereader buffer to create a yuv image but I'm not sure about performance because you need encode using buffer to buffer.
You need get a YUV image in YV12 or NV21 color format and send it to VideoEncoder like here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L311

**Comment by tareqalbeesh** [comment]
could you please provide me with a source to understand how do you get frames from camera in service to stream them, the process seems a bit complicated and I didn't seem to find a documentation for it,
I want to change the source of the frames to be from an ImageReader so I control when to stream them,
my goal mainly is to get frames continuously from ImageReader all the time, and start streaming and stop while maintaining getting frames from camera all the time.

**Comment by pedroSG94** [comment]
I use surface created by MediaCodec to extract surfaces from camera:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L136
I set that surface to Camera api and output buffer of mediacodec is filled automatically each time that Camera api render that surface.
The other way that I mentioned you is used only when you use SurfaceView and Camera1 because that is the only way to encode in API 16-18. This is the only way to encode byte[] directly without use surface from mediacodec.
You have an example to get YUV image from ImageReader here:
https://stackoverflow.com/questions/38325463/android-camera2-i-aquire-yuv-image-from-imagereader-u-and-v-buffers-have-only
