### ISSUE TITLE
how to use FaceDetection？

### ISSUE THREAD

**Issue by fjyuqiang** [pedroSG94/rtmp-rtsp-stream-client-java#822]

**Comment by fjyuqiang** [comment]
i want use FaceDetection，
because RtmpCamera2 get face Data is null。（id=-1，leftEyePosition: null, rightEyePosition: null, mouthPosition: null ）

i code：
-------------------------------------------------------------------------------------------------------------------
mRtmpCamera.enableFaceDetection(new Camera2ApiManager.FaceDetectorCallback() {
            @Override
            public void onGetFaces(Face[] faces) {
//                FaceDetectorUtil faceDetectorUtil = new FaceDetectorUtil();
                for (Face face : faces) {
//                    faceDetectorUtil.camera2Parse(face, openGlView, new PointF()
//                            , CameraHelper.getCameraOrientation(getAttachActivity())
//                            , mRtmpCamera.isFrontCamera());
                    LogUtils.eTag(RTMP_TAG, "face Data" + face);
                }
            }
        });
-------------------------------------------------------------------------------------------------------------------

Data obtained in the log：
-------------------------------------------------------------------------------------------------------------------
{ bounds: Rect(742, 709 - 1448, 1423), score: 90, id: -1, leftEyePosition: null, rightEyePosition: null, mouthPosition: null }
-------------------------------------------------------------------------------------------------------------------

otherwise，FaceDetectorUtil how use？

**Comment by pedroSG94** [comment]
Hello,

This is a bug I will check it. 
About FaceDetectorUtil it is a bit confuse for now. I will refactor it too.

**Comment by pedroSG94** [comment]
Hello,

I modified this feature to work properly and added a page on wiki to explain the use:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Face-detection
My last commit is necessary for it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/1873bae5b7a1744bd4a8b0e93e0f3557a922a343

About mouth and eyes position it is null because you device don't support it. I explained it in my wiki page. To support it you device must support this face detection mode:
https://developer.android.com/reference/android/hardware/camera2/CameraMetadata#STATISTICS_FACE_DETECT_MODE_FULL
I do this check and select it if supported in this line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java#L551

In your case this collection should only contains 1 and 0 values:
https://developer.android.com/reference/android/hardware/camera2/CameraMetadata#STATISTICS_FACE_DETECT_MODE_SIMPLE
https://developer.android.com/reference/android/hardware/camera2/CameraMetadata#STATISTICS_FACE_DETECT_MODE_OFF
