### ISSUE TITLE
Recording Video Without Audio

### ISSUE THREAD

**Issue by tareqalbeesh** [pedroSG94/rtmp-rtsp-stream-client-java#883]
is there anyway to record video without Audio, I mean without even turning the `AudioEncoder `on?
if the library don't support it for now, can you give me an intuition about how to do it.

**Comment by pedroSG94** [comment]
I did a commit for it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/913c8f62fdffc0169f9a250d7dcf20d3fb311dbd

You can stream/record only video if you nerver call prepareAudio method.
This is supported in camera1, camera2 and display modes.
After that. If you want enable audio, stream and record must be stopped in order to call prepareVideo and prepareAudio

**Comment by tareqalbeesh** [comment]
can I stream without audio doing this ?

**Comment by pedroSG94** [comment]
Yes, you can but remember that few server need send audio and video to work or they will close connection.
