### ISSUE TITLE
[Question] can we push stream with previewWidth != videoEncoder.getWidth()?

### ISSUE THREAD

**Issue by mzennis** [pedroSG94/rtmp-rtsp-stream-client-java#889]
So, I need to set the camera preview to fill the entire screen but still maintain the aspect ratio. and, I also want to push the video stream at 1280x720 size.

however, I see that you have a function that forces previewWidth to be equal to the encoder width. Is there any side effect that this value should be the same?
```
if (glInterface == null && !cameraManager.isRunning() && videoEncoder.getWidth() != previewWidth
        || videoEncoder.getHeight() != previewHeight) {
      cameraManager.openLastCamera();
    }
```

**Comment by pedroSG94** [comment]
I have multiple reason for it. For example:

- Avoid differences in stream result and preview because you can select different aspect ratio in each one. Handle all this cases is a pain using opengl and filters like set image, text, gif, etc. Also, you have fill and adjust preview modes that change the logic in all this cases.

- You can't do it in other modes without opengl producing a problem for users to understand the reason because if I use a SurfaceView I can't do it.

- I need duplicate opengl renders that means reduce performance that could increase so much in extreme cases like:
I use preview in 4k but stream in 720p. That means that you need handle with 2 renders. Preview render in 4k and stream render in 4k but resized to 720p.

**Comment by mzennis** [comment]
ahh okay, I think this enough for now. Thank you @pedroSG94
