### ISSUE TITLE
PedroSG94 RTMP-STSP-Stream-Client SDK with ARCore SDK for Live Streaming in Android

### ISSUE THREAD

**Issue by ntqp97** [pedroSG94/rtmp-rtsp-stream-client-java#907]
As title, has anyone tried integrating ARCore into RTMP-STSP-Stream-Client SDK? please help me!!!

**Comment by pedroSG94** [comment]
Hello, 

I can see that you found this issue: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/724
I haven't anything more to add about it and my suggest is still the same.
I haven't plan to integrate a official solution for this because the list of supported devices is limited and it is not required by most of users
