### ISSUE TITLE
Can "I/RtmpSender: Skipping iteration, frame null" cause a stream to not connect?

### ISSUE THREAD

**Issue by HirogaKatageri** [pedroSG94/rtmp-rtsp-stream-client-java#911]
We are having a few issues where RtmpSender is sending video and audio frames, but somehow the content isn't being shown.
I noticed RtmpSender would have a log "Skipping iteration, frame null" would this be a possible cause as to why the content isn't being reflected?

On my end it is working fine, this only happens to some people. I'm wondering whether it is a connection issue though.

**Comment by pedroSG94** [comment]
Hello,

That log only indicate that framequeue was waiting for a frame 1s but any frame was received and skip that loop iteration.

This is not related with your case. First of all, you need know if you receive frames in server side (check if you get keyframes in video source because it is the most important frame to avoid video problem). Remember that few platform only work if you send audio and video. Only one is not supported (YouTube for example).

If you have internet problem you can see in logs "Video/Audio frame discarded" because your cache queue is full and you start to discard frames in order to preserve memory.
hasCongestion method provide you a way to know if you have internet problems. Also, you can check bitrate in  onNewBitrate callback to know if bps is close to the selected for you indicating that you have internet problems or not.

Other good idea is create a way to received device information to know how to what happens.
Using google analitycs you can send codec info of each device (using CodecUtil.showAllCodecsInfo()) and send you a report if you have internet problems to discard it

**Comment by HirogaKatageri** [comment]
Got it, thanks for this, we were doing the testing on Youtube and I'm guessing probably either the video or audio wasn't able to initialize or the internet wasn't stable enough to allow the stream status to be updated. On my end and others, it was stable, it was only with a few others that it wasn't.
