### ISSUE TITLE
Simple question... PROPERTY_OUTPUT_FRAMES_PER_BUFFER

### ISSUE THREAD

**Issue by JDBae** [pedroSG94/rtmp-rtsp-stream-client-java#928]
I like to know which  is represented for PROPERTY_OUTPUT_FRAMES_PER_BUFFER in Audio and encoder .

thanks

**Comment by pedroSG94** [comment]
I use this method to get buffer size:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/226b1a56f0ac5dfecd09a1aa401046232c4d514f/encoder/src/main/java/com/pedro/encoder/input/audio/MicrophoneManager.java#L223

**Comment by JDBae** [comment]
thanks

**Comment by JDBae** [comment]
Another simple question...

Would you explain why 5 time size of buffer is required...

 in your program...
 private int getPcmBufferSize() {
    BUFFER_SIZE = AudioRecord.getMinBufferSize(sampleRate, channel, audioFormat);
    pcmBuffer = ByteBuffer.allocateDirect(BUFFER_SIZE);
    pcmBufferMuted = new byte[BUFFER_SIZE];
    return BUFFER_SIZE * 5;

**Comment by pedroSG94** [comment]
Years ago (when I started to develop this library) I experimented problems with few devices that crash or produce desynchronization audio using minbuffersize so I set a value inspired in this line:
https://github.com/begeekmyfriend/yasea/blob/fba1588ad6c317ea2ea9b03491d92f339bbc8185/library/src/main/java/net/ossrs/yasea/SrsEncoder.java#L551
I used 5 to be sure avoid this crash since 4 sometimes still produce the problem.

Remove or reduce this value could be possible but since It is working fine without problems I don't want change it
