### ISSUE TITLE
wrote Video packet is not work at Background service example 

### ISSUE THREAD

**Issue by featherfly** [pedroSG94/rtmp-rtsp-stream-client-java#974]
when i run Background service example push to a rtmp resource 
there is only wrote Audio packet in logcat (no wrote Video packet)
but other example such as default rtmp, opengl rtmp is work ok

the work device is a android board with usb camera

**Comment by featherfly** [comment]
i found the problem
Camera2ApiManager is not work ok with usb camera

**Comment by pedroSG94** [comment]
Sorry, but usb camera is not supported because most of device can't do it (I never found a device with UVC support in camera 2 api). Since it isn't a common case, I will not develop a feature that only works in a very limited number of devices. 

If you want you can check Camera2ApiManager class and fix it yourself.
I hope you understand, but I can't help you so much about it because I haven't a way to test it, but I could response you any question about the current code.

**Comment by featherfly** [comment]
thx for the lib, it very useful 
now it work ok
i just return the first camera when camera is not found

Log.e(TAG, "Camera not supported"); // TODO maybe we want to throw some exception here?
// this is my code 
if (cameraManager.getCameraIdList() != null && cameraManager.getCameraIdList().length > 0) {
  Log.i(TAG, "open first camera");
  openCameraId(Integer.parseInt(cameraManager.getCameraIdList()[0]));
}

maybe add a config param to enable or disable this future

**Comment by featherfly** [comment]
thx for the lib, it very useful
now it work ok

the problem in the example RtpService prepareStreamRtp() is not use the preview RtmpCamara2 object, so it always use the default Facing

**Comment by pedroSG94** [comment]
I'm glad that it is working now.
Maybe the problem was that your camera is not detected as front or back camera but you still can open it.
I tought that you was using a normal device with UVC camera connected. If you want you can create a PR to add this feature to the library.
