### ISSUE TITLE
SrsFlvMuxer: frame discarded

### ISSUE THREAD

**Issue by colax** [pedroSG94/rtmp-rtsp-stream-client-java#98]
Hi, 

Firstly, my congratulations for sharing this repository.

I'm recently loaded all your examples in a Xiaomi redmi 4A and SGalaxy S8. Both of them show me: **SrsFlvMuxer: frame discarded** when I attempted to connect to my Unreal media server through RTMP. No matter wihich of the different examples I'm using. I tried to vary the main parameters (bitrate and so on) but still the same.
App shows: Connection failed, Fail to connect timeout.

I'm copying more logcat info maybe useful:

_I/VideoEncoder: Color supported: 2135033992
I/VideoEncoder: Color supported: 19
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
D/RtmpConnection: wrote packet: RTMP Command (command: connect, transaction ID: 1), size: 272
I/Camera1ApiManager: 640X480
I/MediaCodec: onMessageReceived(kWhatOutputFormatChanged), prependSPSPPS 0
I/SrsFlvMuxer: flv: h264 sps/pps sent, sps=9B, pps=4B_

Any ideas?
Thanks in advance Pedro.

**Comment by pedroSG94** [comment]
If you can't connect to server **SrsFlvMuxer: frame discarded** is not important. This tell you that queue in SrsFlvMuxer class is full and can't get more frames, in this case this is because you are not connected to the server and then library never send a packet, so you are accumulating packets in the queue and discard frames to preserve memory.

The problem is timeout, I recommend you test it:
- I did a stream with a early version of this library to Unreal media server and I had problems with the I-frame, If I remember good, I set I-frame to 5 and work. https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L113
- Check if you have a server configuration problem or your endpoint is not correct. The best way is use Ffmpeg to stream a mp4 from desktop. Use other PC, not the same PC where you installed server to discard network problems (routing, ports, etc). If you can't stream with ffmpeg then this is a server fail configuration but if ffmpeg is working then let me know it and I will try install a Unreal media server and test. If you can share a link with installation and configuration page to create a server with same version and configuration.

**Comment by colax** [comment]
Hey Pedro, thanks.

I've tried with I-frame but still the same.
I tried to broadcast from ffmpeg, but I dunno if I'm missing something or just Im doing it in error:
ffmpeg -f dshow -i video="UScreenCapture" -f flv rtmp://ip:5130/live/check
then I got  rtmp://....   I/O error. Is this the right command?
I'm using UMS v11.0.

This is not the first time that I have troubles with rtmp apps and unreal media server. Actually I tried in Wowza and works right away.

**Comment by pedroSG94** [comment]
You have ffmpeg command in this post:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/88
Share me a unreal media server instalation. In linux if you can

**Comment by JosebaRuizO** [comment]
Alright I got the ffmpeg streaming successfully.
http://umediaserver.net/umediaserver/faq.html

**Comment by JosebaRuizO** [comment]
Alright I got the ffmpeg streaming successfully.
Just in case someone would need it. I had some issues there is a how to there: 
> http://umediaserver.net/umediaserver/faq.html -> How to push a live stream to Unreal Media Server with ffmpeg?

This is the server: http://umediaserver.net/bin/UMediaServer(x64).zip

**Comment by colax** [comment]
Alright I got the ffmpeg streaming successfully.
Just in case someone would need it. I had some issues there is a how to there:

> http://umediaserver.net/umediaserver/faq.html -> How to push a live stream to Unreal Media Server with ffmpeg?

In the FAQ, you have there how the url should looks like:

> What live encoders can push a stream to Unreal Media Server and how should they be configured?

"rtmp://192.168.1.8:5130/live/Camera8"
I tried the one I used for Ffmpeg but doesnt work neither: "rtmp://192.168.1.8:5130/live/Camera8/livestream"

This is the server: http://umediaserver.net/bin/UMediaServer(x64).zip

**Comment by pedroSG94** [comment]
I tried stream to the unreal media server with ffmpeg but it is not working. Same problem that with my library timeout from socket connection.
![captura de pantalla de 2017-12-10 13-18-00](https://user-images.githubusercontent.com/17556876/33804769-98b8be0e-ddac-11e7-9616-acaf4181904c.png)
I used this configuration application with this command in ffmpeg:
```
ffmpeg -i ./Vídeos/big_buck_bunny_480p_h264.mov -f flv rtmp://192.168.178.42:5130/app/pedro
```
I will try more but this look bad :(

**Comment by colax** [comment]
try this pedro, it worked for me:

ffmpeg -i ./Vídeos/big_buck_bunny_480p_h264.mov -f flv rtmp://192.168.178.42:5130/app/pedro/livestream

In the FAQ link, they said you need to add "/livestream" at the end.
Actually, with BroadcastMe an Streamaxia app, i needed to do like this too. If not, it didnt broadcast my rtmp feed.

**Comment by pedroSG94** [comment]
Not working with ffmpeg. Will try more, maybe some configuration is bad.

**Comment by colax** [comment]
What if you try the url from the faq?

> ffmpeg -re -i ./Vídeos/big_buck_bunny_480p_h264.mov -acodec copy -vcodec copy -f flv rtmp://192.168.178.42:5130/live/app/livestream

**Comment by pedroSG94** [comment]
Same problem. I will try look other tutorial or something
