### ISSUE TITLE
Add the date time in the video streaming to server

### ISSUE THREAD

**Issue by Shanmugamsundarrajan** [pedroSG94/rtmp-rtsp-stream-client-java#997]
How to Add the date time in the video streaming to server, Is there any option by which I can do it.
Please let me know. The need is to show the date time in the streaming video.

**Comment by pedroSG94** [comment]
Hello,

I deleted the diccussion because it is duplicated.
About the issue, you can do it with filters. Check OpenGl example where you can find how to send android views or text to stream using filters:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L164
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L315
